### PR TITLE
Merge dev GA v1.0.0 to master branch 

### PR DESCRIPTION
**Pull request by shay-berman**
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/162)

### CODE REVIEW

**Comment by ranhrl** [comment]
:lgtm:

---

Review status: 0 of 59 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/162#-:-L0ieu42kvM1zwS2ECex:bnfp4nl)*

**Comment by ranhrl** [comment]
Reviewed 60 of 60 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/162)*

**Comment by shay-berman** [comment]
Reviewed 60 of 60 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/162)*

**Comment by shay-berman** [comment]
All tests passed OK,   merging to master.  
Soon GA time :-)

**Pull request merged**
