### PR TITLE
Feature/ub 159 vol mig

### PR DESCRIPTION
**Pull request by liortamari**
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/110)

### CODE REVIEW

**Comment by shay-berman** [comment]
Review status: 0 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[glide.yaml, line 11 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPDRFewgArEnnZClMn:-KxPDRFgWiJ5m7gBxLMw:b-d4zwt9) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/glide.yaml#L11)):*
> ```YAML
>   - lib/leaderelection
> - package: github.com/IBM/ubiquity
>   version: 29836e2f14afcfac6312baa03f89cd9b8eb64822
> ```

just reminder to set it back to dev before you merge it to dev

---

*[controller/controller.go, line 95 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPE0Q8liqbpoj0K-vC:-KxPE0Q8liqbpoj0K-vD:b-a5l13) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9f8dfb6707f0eb35f316632b034b9f9b924caf2f/controller/controller.go#L95)):*
> ```Go
> 	defer c.logger.Println("controller-attach-end")
> 
> 	if attachRequest.Version == k8sresources.KubernetesVersion_1_5 {
> ```

R u sure you don't need to do any specific code for k8s 1.5 like we had here?   just asking, since I am not sure.

---

*[controller/controller.go, line 126 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPEJEujo8VtKSDOtGt:-KxPEJEujo8VtKSDOtGu:b-33yhgj) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L126)):*
> ```Go
> 
> 
> //GetVolumeName checks if volume is attached
> ```

is this correct docstring?

---

*[controller/controller.go, line 133 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPENg4DghueW7KgTv1:-KxPENg5hNGHinbX5cyn:b8ksxdb) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L133)):*
> ```Go
> 
> 	response = k8sresources.FlexVolumeResponse{
> 		Status: "Not supported",
> ```

so whats new here?   is it ok not to support it?

---

*[controller/controller.go, line 147 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPEXR5762yVE7EU2WP:-KxPEXR5762yVE7EU2WQ:b-802c8i) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L147)):*
> ```Go
> 
> 	response = k8sresources.FlexVolumeResponse{
> 		Status: "Not supported",
> ```

does it ok not to implement it ?

---

*[controller/controller.go, line 154 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPEtJ7bArJTL2VZYuA:-KxPEtJ7bArJTL2VZYuB:b-fbthgn) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L154)):*
> ```Go
> }
> 
> //IsAttached checks if volume is attached
> ```

please mention if this function called by the controller or by kubelet or by both.
so it will be easier to understand it.

---

*[controller/controller.go, line 206 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPGqRJVoCxAxz7896B:-KxPGqRJVoCxAxz7896C:bdu698k) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L206)):*
>  c.logger.Trace(logs.DEBUG)()
> 	var response k8sresources.FlexVolumeResponse
> 	c.logger.Debug("", logs.Args{{"request", mountDeviceRequest}})
can u shrink all these boilerplate , maybe with one defer function that print log the request and response?

---

*[controller/controller.go, line 223 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPH71y8OswzngN_pxD:-KxPH71y8OswzngN_pxE:b-p65mdi) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L223)):*
> ```Go
> 
> 	response = k8sresources.FlexVolumeResponse{
> 		Status: "Not supported",
> ```

explain why we are not supporting it and who is calling it?

---

*[controller/controller.go, line 236 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPHU5EvIQ-mjiQeETQ:-KxPHU5EvIQ-mjiQeETR:bwc6hzh) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L236)):*
> ```Go
> 	c.logger.Debug("", logs.Args{{"request", mountRequest}})
> 
> 	mountedPath, err := c.doMount(mountRequest)
> ```

does it still support 1.5?   

---

*[controller/controller.go, line 335 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPHvHsKWcy33pu_x1j:-KxPHvHsKWcy33pu_x1k:bcskaq5) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L335)):*
> ```Go
> 	}
> 
> 	wwn, ok := mountRequest.Opts["Wwn"]
> ```

how it was handle by scale?

---

*[scripts/build_flex_driver, line 8 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPJCUf3rI301mLT538:-KxPJCUgFm_EKxco_iUG:b-1akjlc) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/scripts/build_flex_driver#L8)):*
> ```
> 
> echo "Building flex driver"
> go build -ldflags '-w -linkmode external -extldflags "-static"' -o  $scripts/../bin/ubiquity-k8s-flex $scripts/../cmd/flex/main/cli.go
> ```

why do you  need this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110)*

**Comment by liortamari** [comment]
*[controller/controller.go, line 95 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPE0Q8liqbpoj0K-vC:-Kyq1_TetNK2EhZDK6uE:bdemyw5) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9f8dfb6707f0eb35f316632b034b9f9b924caf2f/controller/controller.go#L95)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

R u sure you don't need to do any specific code for k8s 1.5 like we had here?   just asking, since I am not sure.
</blockquote></details>

yes in 1.5 there is attach with hostname that we guess

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110)*

**Comment by liortamari** [comment]
*[controller/controller.go, line 133 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPENg4DghueW7KgTv1:-Kyq2ATF63NFnHjOZg7N:buy9jpj) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L133)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

so whats new here?   is it ok not to support it?
</blockquote></details>

GetVolumeName is optional in kuberenetes as i understand

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110)*

**Comment by liortamari** [comment]
*[controller/controller.go, line 147 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPEXR5762yVE7EU2WP:-Kyq2I1NFjjnfK3yFH-A:bxwr4m0) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L147)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

does it ok not to implement it ?
</blockquote></details>

it will work ok since our attach is actually sync

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110)*

**Comment by liortamari** [comment]
*[controller/controller.go, line 154 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPEtJ7bArJTL2VZYuA:-Kyq2Ru4nQAjqM0eL4p2:b2u2i2b) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L154)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

please mention if this function called by the controller or by kubelet or by both.
so it will be easier to understand it.
</blockquote></details>

i think all entities in kubernetes are allowed (and do) call it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110)*

**Comment by liortamari** [comment]
*[controller/controller.go, line 206 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPGqRJVoCxAxz7896B:-Kyq2o4PwdD0tQRtE4Pg:bmm54bd) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L206)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

>  c.logger.Trace(logs.DEBUG)()
> 	var response k8sresources.FlexVolumeResponse
> 	c.logger.Debug("", logs.Args{{"request", mountDeviceRequest}})
can u shrink all these boilerplate , maybe with one defer function that print log the request and response?
</blockquote></details>

in each API function enter we print to the log the request
in each API function exit we print to the log the response.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110)*

**Comment by liortamari** [comment]
*[controller/controller.go, line 223 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPH71y8OswzngN_pxD:-Kyq3-Td4-x4S7GzmR6n:bfsz74f) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L223)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

explain why we are not supporting it and who is calling it?
</blockquote></details>

mount/unmount device are for cases that multiple containers use the same volume.
according to ran that is unsupported now in ubiquity

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110)*

**Comment by liortamari** [comment]
*[controller/controller.go, line 236 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPHU5EvIQ-mjiQeETQ:-Kyq3AzDzl1UKMszWIH2:bjadla4) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L236)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

does it still support 1.5?   
</blockquote></details>

yes 1.5 mount/unmount is still supported

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110)*

**Comment by liortamari** [comment]
*[scripts/build_flex_driver, line 8 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPJCUf3rI301mLT538:-Kyq3YU2wQLAwZFL4tz-:b8tjkkb) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/scripts/build_flex_driver#L8)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

why do you  need this change?
</blockquote></details>

it was temp

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110)*

**Comment by liortamari** [comment]
*[controller/controller.go, line 335 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110#-KxPHvHsKWcy33pu_x1j:-Kyq4uCM4eJYQteHYAcP:b-z14g11) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ca6182af01d1de6cd258cce12fce0bda8900c97c/controller/controller.go#L335)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

how it was handle by scale?
</blockquote></details>

before the changes, the mountedPath would come back from Attach.
now we dont have this option.
so ssc should change this code based on their mountedPath 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/110)*

**Pull request closed without merging**
