### PR TITLE
Feature/flex daemonset also run on masters + change flex directory

### PR DESCRIPTION
**Pull request by shay-berman**
1. Run Daemonset on masters as well by using "tolerations" tag. 
2. In addition change the directory of the flex config + log + certificate into the same directory of the binary file /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ibm~ubiquity-k8s-flex
3. Some text fixes per code review.

Full details -> #116

The PR passed sanity (and also sanity with certificates \ verify-full)

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/122)

### CODE REVIEW

**Comment by ranhrl** [comment]
Review status: 0 of 16 files reviewed at latest revision, 10 unresolved discussions.

---

*[ubiquity-k8s-provisioner.conf, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMoEFYPU6h8EeCNSBJ:-KyMoEFYPU6h8EeCNSBK:b-hvulo1) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/ubiquity-k8s-provisioner.conf#L1)):*
> ```
> # NOTE : This script is obsolete because ubiquity is been installed as docker image.
> ```

If it's obsolete then why don't you delete it?

---

*[cmd/flex/main/cli.go, line 42 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMoPCRQth_fU4oG5BT:-KyMoPCRQth_fU4oG5BU:b8xutxe) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/cmd/flex/main/cli.go#L42)):*
> ```Go
> 	"configFile",
> 	k8sresources.FlexConfPath,
> 	"config file with ubiquity client configuration params",
> ```

If the use see this description, it should be reviewed by Dima. Anyway, I would change to "Flex Volume configuration file, containing Ubiquity connection parameters."

---

*[deploy/k8s_deployments/setup_flex.sh, line 16 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMpJV84s_k_6kIo4TC:-KyMpJV84s_k_6kIo4TD:b-s7ors4) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/deploy/k8s_deployments/setup_flex.sh#L16)):*
> ```Shell
> if [ ! -d "${MNT_FLEX_DRIVER_DIR}" ]; then
>   echo "Creating the flex driver directory [$DRIVER] for the first time."
>   echo "***Attention*** : Kubernetes version below 1.8 - the user must restart manually the kubelet service in order to load the new flex driver."
> ```

All echo statements should be reviewed by Dima. 

"If you are running on a Kubernetes version which is lower then 1.8, a restart to the kubelet service is required to take affect."

---

*[deploy/k8s_deployments/setup_flex.sh, line 20 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMpzZMwm63QR5S80aR:-KyMpzZMwm63QR5S80aS:b-wx6wwa) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/deploy/k8s_deployments/setup_flex.sh#L20)):*
> ```Shell
> fi
> 
> echo "Copying the flex driver ~/$DRIVER into ${MNT_FLEX_DRIVER_DIR} directory"
> ```

be consistent with "." at the end of a sentence.

---

*[deploy/k8s_deployments/setup_flex.sh, line 24 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMq3fZRpCzB1kRG_Hp:-KyMq3fZRpCzB1kRG_Hq:b-cdetdx) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/deploy/k8s_deployments/setup_flex.sh#L24)):*
> ```Shell
> mv -f "${MNT_FLEX_DRIVER_DIR}/.$DRIVER" "${MNT_FLEX_DRIVER_DIR}/$DRIVER"
> 
> echo "Copying the flex config file ${FLEX_CONF_PATH} to ${MNT_FLEX_DRIVER_DIR}/${FLEX_CONF}"
> ```

same here "."

---

*[deploy/k8s_deployments/setup_flex.sh, line 28 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMqHRP_Il-wWTmm3zN:-KyMqHRP_Il-wWTmm3zO:b6850qu) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/deploy/k8s_deployments/setup_flex.sh#L28)):*
> ```Shell
> cp ${FLEX_CONF_PATH} ${FLEX_TMP}
> if [ -n "$UBIQUITY_USERNAME" ]; then
>     echo "Update \"username\" in config file based on environment UBIQUITY_USERNAME"
> ```

Updating based on environment variable.

---

*[deploy/k8s_deployments/setup_flex.sh, line 62 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMr0RwOvResexZWdHq:-KyMr0RwOvResexZWdHr:bj33whj) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/deploy/k8s_deployments/setup_flex.sh#L62)):*
> ```Shell
>    fi
> else
>        echo "The ubiquity public certificate ENV UBIQUITY_PLUGIN_VERIFY_CA is empty, so cannot copy the certificate to ${MNT_FLEX_DRIVER_DIR}"
> ```

You just need to say that it's not set and the server certificate will not be verified. I am not sure that all those Variable names help the user, instead instruct him that if he requires to verify the certificate, then point him to the guide to take the next steps.

Same if verification is set.

---

*[deploy/k8s_deployments/ubiquity_flex_daemonset.yml, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMrU5PnaPTVNWrkwJS:-KyMrU5QWjYO249xxTht:b-6uqxst) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/deploy/k8s_deployments/ubiquity_flex_daemonset.yml#L1)):*
> ```YAML
> # NOTE : This script is obsolete - go to scripts/installer-for-ibm-storage-enabler-for-containers
> ```

obsolete ===> delete it

---

*[deploy/k8s_deployments/ubiquity-configmap/ubiquity-k8s-flex.conf, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMrYG5OCJxF1XNbYiw:-KyMrYG5OCJxF1XNbYix:b-2guby3) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/deploy/k8s_deployments/ubiquity-configmap/ubiquity-k8s-flex.conf#L1)):*
> ```
> # NOTE : This script is obsolete - go to scripts/installer-for-ibm-storage-enabler-for-containers
> ```

same here

---

*[scripts/ubiquity-k8s-provisioner.env, line 5 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMrqDWx_GDEd_xSVNc:-KyMrqDWx_GDEd_xSVNd:b-kfvgdh) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/scripts/ubiquity-k8s-provisioner.env#L5)):*
> ```
> 
> # NOTE : This script is obsolete because ubiquity is been installed as docker image.
> ```

delete it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122)*

**Comment by ranhrl** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122)*

**Comment by shay-berman** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[ubiquity-k8s-provisioner.conf, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMoEFYPU6h8EeCNSBJ:-KyMwdXXWFITWdMCI-Ei:badlp19) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/ubiquity-k8s-provisioner.conf#L1)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

If it's obsolete then why don't you delete it?
</blockquote></details>

Opened a ticket for this cleanup since we should consider to keep some of them with adjustments -> UB-443

---

*[cmd/flex/main/cli.go, line 42 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMoPCRQth_fU4oG5BT:-KyMyURMPToYnT0ru-md:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/cmd/flex/main/cli.go#L42)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

If the use see this description, it should be reviewed by Dima. Anyway, I would change to "Flex Volume configuration file, containing Ubiquity connection parameters."
</blockquote></details>

Done.

---

*[deploy/k8s_deployments/setup_flex.sh, line 16 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMpJV84s_k_6kIo4TC:-KyMyv-hUpbyqZDDP6Z4:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/deploy/k8s_deployments/setup_flex.sh#L16)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

All echo statements should be reviewed by Dima. 

"If you are running on a Kubernetes version which is lower then 1.8, a restart to the kubelet service is required to take affect."
</blockquote></details>

Done.

---

*[deploy/k8s_deployments/setup_flex.sh, line 20 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMpzZMwm63QR5S80aR:-KyMzEB94DS6gu47v2oY:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/deploy/k8s_deployments/setup_flex.sh#L20)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

be consistent with "." at the end of a sentence.
</blockquote></details>

Done.

---

*[deploy/k8s_deployments/setup_flex.sh, line 24 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMq3fZRpCzB1kRG_Hp:-KyMzF2hkYkBmahpcODW:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/deploy/k8s_deployments/setup_flex.sh#L24)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

same here "."
</blockquote></details>

Done.

---

*[deploy/k8s_deployments/setup_flex.sh, line 28 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMqHRP_Il-wWTmm3zN:-KyMzZ0b2iCAFPjwqoLm:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/deploy/k8s_deployments/setup_flex.sh#L28)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

Updating based on environment variable.
</blockquote></details>

Done.

---

*[deploy/k8s_deployments/setup_flex.sh, line 62 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMr0RwOvResexZWdHq:-KyN0Mwi4JCNtCDNlXxy:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/deploy/k8s_deployments/setup_flex.sh#L62)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

You just need to say that it's not set and the server certificate will not be verified. I am not sure that all those Variable names help the user, instead instruct him that if he requires to verify the certificate, then point him to the guide to take the next steps.

Same if verification is set.
</blockquote></details>

Done.

---

*[deploy/k8s_deployments/ubiquity_flex_daemonset.yml, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMrU5PnaPTVNWrkwJS:-KyN0dTPYKG6oQiGWKsc:br26w62) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/deploy/k8s_deployments/ubiquity_flex_daemonset.yml#L1)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

obsolete ===> delete it
</blockquote></details>

Done.
This is for sure need to be deleted.

---

*[deploy/k8s_deployments/ubiquity-configmap/ubiquity-k8s-flex.conf, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMrYG5OCJxF1XNbYiw:-KyN0qWsctgtQgVv9tae:bxi6n4l) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/deploy/k8s_deployments/ubiquity-configmap/ubiquity-k8s-flex.conf#L1)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

same here
</blockquote></details>

it with scale params.
Lets scrub it later on please.

---

*[scripts/ubiquity-k8s-provisioner.env, line 5 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyMrqDWx_GDEd_xSVNc:-KyN157dBXxPwOoRrYlR:bhcl5x0) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/7324307e6b15ea4bda4b66755c4b57829466b63a/scripts/ubiquity-k8s-provisioner.env#L5)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

delete it
</blockquote></details>

part of UB-443

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122)*

**Comment by liortamari** [comment]
*[scripts/installer-for-ibm-storage-enabler-for-containers/scbe-credentials.yml, line 11 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyP_C77iMrkzA8U67A2:-KyP_C77iMrkzA8U67A3:b5lyw5r) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/bba9982c08da8ff2174ef1ead5702765b786998e/scripts/installer-for-ibm-storage-enabler-for-containers/scbe-credentials.yml#L11)):*
> ```YAML
>    username: "SCBE_USERNAME_VALUE"
> 
>    # Base64 encoded password defined for SCBE Ubiquity interface.
> ```

something i am missing here. are we still calling it ubiquity interface?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122)*

**Comment by liortamari** [comment]
*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh, line 13 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122#-KyP_SvWZPmYzLMwn28p:-KyP_SvWZPmYzLMwn28q:b-7ilvfu) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/bba9982c08da8ff2174ef1ead5702765b786998e/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh#L13)):*
> ```Shell
> #   3. Create ubiquity-k8s-provisioner deployment
> #   4. Create ubiquity-k8s-flex Daemonset
> #   5. Create ubiquity-db-deployment deployment  (This step uses PVC, so ubiqiuty must be up and ready for it)
> ```

typo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122)*

**Comment by liortamari** [comment]
Reviewed 13 of 16 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/122)*

**Pull request merged**
