### PR TITLE
UB-1001: fix idempotent - calling detach with an empty host -> not at…

### PR DESCRIPTION
**Pull request by olgashtivelman**
fixing an idempotent issue of unmounting a volume which does not exist or is already detached.

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/197)

### CODE REVIEW

**Comment by olgashtivelman** [comment]
( @shay-berman - note : we discussed a different solution but the reason I am not just passing "true" as we discussed earlier is because of the implementation of checking whether a volume is attached or not )

---

Review status: 0 of 2 files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/197#-:-LFr3Ff2EQ36eHx3mWzr:bqzsf5)*

**Comment by shay-berman** [comment]
Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @olgashtivelman and @shay-berman)

---

*[controller/controller.go, line 741 at r1](https://reviewable.io/reviews/ibm/ubiquity-k8s/197#-LG-aC8TCiqF65jUb95K:-LG-aC8U2jQ1xMKXGkGi:bophas5) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/29fc7a2eec7c62078fbc6240f96b1e9cc2a4f053/controller/controller.go#L741)):*
> ```Go
> 	}
> 	
> 	if host == "" {
> ```

its strange that you have another if host=="" in the same level of the previuos
 please move it 2 lines upper so it will be after checking error from c.getHostAttached so if no error then we double check the host.  Then it get into the context of the "//only when triggered during unmount"

---

*[controller/controller_test.go, line 656 at r1](https://reviewable.io/reviews/ibm/ubiquity-k8s/197#-LG-b95yA_JRwJ2vKDlv:-LG-b95yA_JRwJ2vKDlw:b-6yv1e8) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/29fc7a2eec7c62078fbc6240f96b1e9cc2a4f053/controller/controller_test.go#L656)):*
> ```Go
> 	*/
> 	Context(".Detach", func() {
> 		BeforeEach(func() {
> ```

also please make sure you rebase from dev, since its alread include other improvment in the unmount flow (i don;t think you will have collision but its better to check)

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/197)*

**Comment by olgashtivelman** [comment]
Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @shay-berman)

---

*[controller/controller.go, line 741 at r1](https://reviewable.io/reviews/ibm/ubiquity-k8s/197#-LG-aC8TCiqF65jUb95K:-LG0Szbl8PQKT6tft4dN:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/29fc7a2eec7c62078fbc6240f96b1e9cc2a4f053/controller/controller.go#L741)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

its strange that you have another if host=="" in the same level of the previuos
 please move it 2 lines upper so it will be after checking error from c.getHostAttached so if no error then we double check the host.  Then it get into the context of the "//only when triggered during unmount"
</blockquote></details>

Done.

---

*[controller/controller_test.go, line 656 at r1](https://reviewable.io/reviews/ibm/ubiquity-k8s/197#-LG-b95yA_JRwJ2vKDlv:-LG0SNQV0uNVIiR-ABW6:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/29fc7a2eec7c62078fbc6240f96b1e9cc2a4f053/controller/controller_test.go#L656)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

also please make sure you rebase from dev, since its alread include other improvment in the unmount flow (i don;t think you will have collision but its better to check)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/197)*

**Comment by olgashtivelman** [comment]
@shay-berman - please see the changes as per your comments

---

Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @shay-berman)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/197#-:-LG0TC0y9ow8CgZ-YIlV:b-9ihauc)*

**Comment by shay-berman** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/197)*

**Comment by shay-berman** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/197#-:-LG5Ms-K-ewKeU9FJ_1T:bnfp4nl)*

**Pull request merged**
