### PR TITLE
Fix/ub 1087 isattach succeed if vol does not exist

### PR DESCRIPTION
**Pull request by olgashtivelman**
This PR will make sure that isAttached API will not fail with an error if volume does not exist (causing the master-flex to go into a loop of calling isAttached) .
if isAttached encounters a "vol <volume> does not exist" error it will return false and not raise an exception.

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/198)

### CODE REVIEW

**Comment by shay-berman** [comment]
Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @olgashtivelman and @shay-berman)

---

*[controller/controller.go, line 762 at r1](https://reviewable.io/reviews/ibm/ubiquity-k8s/198#-LG5NRLk1S9GF0MoPNgR:-LG5NRLlC8kKL_uloP1Q:bpt2jsp) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e5af89023e75d8349fc0bf2c4296fd2e88734a4f/controller/controller.go#L762)):*
> ```Go
> 	attachTo, err := c.getHostAttached(volName, isAttachedRequest.Context)
> 	if err != nil {
> 		matched, _ := regexp.MatchString("^volume .* not found$", err.Error())
> ```

please instead of hardcoded this regex, you should do the same i did in Unmount(),    check for "strings.Contains(err.Error(), resources.VolumeNotFoundErrorMsg)"  (more detail u can see in the PR -> https://github.com/IBM/ubiquity/pull/216)

please make sure that this is the error return from getHostAttached if the volume is not exist). in the unmount it was from the "Client.GetVolume interface"  so please check its the same for the relevant call from the getHostAttached function.

Thanks

---

*[controller/controller.go, line 764 at r1](https://reviewable.io/reviews/ibm/ubiquity-k8s/198#-LG5OSBAARRPas3ziFMG:-LG5OSBAARRPas3ziFMH:b-dpd7lo) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e5af89023e75d8349fc0bf2c4296fd2e88734a4f/controller/controller.go#L764)):*
> ```Go
> 		matched, _ := regexp.MatchString("^volume .* not found$", err.Error())
> 		if matched {
> 			c.logger.Warning(fmt.Sprintf("Idempotent issue. error captured : %s. returning isAttached=False" , err))
> ```

please put this text in the error.go file, and make it more clear that isAttach didn't find the PV so it return isattached=false.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/198)*

**Comment by YuDaiWang** [comment]
image
I test use isattached command. the volumeName is NULL in the return results, why not put volumeName in it?

**Comment by YuDaiWang** [comment]
image
log message is not readable

**Comment by olgashtivelman** [comment]
@YuDaiWang I am not sure what this comment is related to, and what is the relation to the code review? 

---

Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @olgashtivelman and @shay-berman)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/198#-:-LGUxfGEBnyvalmMWxVb:b-qzwe5c)*

**Comment by shay-berman** [comment]
@olgashtivelman  what is the status of this PR?
what is the jira ticket for it?

**Comment by olgashtivelman** [comment]
this PR is no longer relevant since this issue is not reproducable, so I am closing this for now.

**Pull request closed without merging**
