### PR TITLE
bumped latest external-storage

### PR DESCRIPTION
**Pull request by midoblgsm**
Signed-off-by: Mohamed Mohamed <mmohamed@us.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/80)

### CODE REVIEW

**Comment by shay-berman** [comment]
@midoblgsm  please provide more detail about this PR.
is this relevant for GA?

**Comment by midoblgsm** [comment]
this resolves #97 , basically it gets the latest code developed by k8s community for dynamic provisioning 

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/80#-:-KwD1H_-2UbRsBLJI3T5:b4fi4kl)*

**Comment by shay-berman** [comment]
Hi Mohamed

Need some clarification here
it looks like this PR contain 3 different features:
1. upgrade to golan 1.9.1
2. update the k8s external-storage import (from specific version to master branch)
3. some Spectrum Scale NFS changes
4. removal of identify file

probably i miss here something, but is there any reason why all of them in the same PR?  any relationship between them that I am missing?   or u just want to push multiple features in single PR? 

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/k8s_deployments/ubiquity_provisioner_deployment.yml, line 20 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/80#-KwGXuhUzhAk0NBD7Ro6:-KwGXuhUzhAk0NBD7Ro7:b-3nt5l8) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/738b481382d5bdce903eaa86186903c72abdae6b/deploy/k8s_deployments/ubiquity_provisioner_deployment.yml#L20)):*
> 
Can you please explain why you removed the RETRIES?
The new provisioner code, doesn't need it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/80#-:-KwGY_a6QImd9Mrq3hj4:bh6b8aw)*

**Comment by midoblgsm** [comment]
I started by creating three different PRs each having one item. After that, since I needed to test with the latest change for the storageClassNAme issue (#97), I just did the changes which are really minor and do not need big review (1.9 => 1.9.1 and 3 lines in utils to get ssc nfs param). I decided to have them in one PR.

Retries are removed since they are not required anymore in the new external storage code.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/80#-:-KwGjxyI8BFl4oEAKOMl:bth55c)*

**Comment by shay-berman** [comment]
it was a bit confusing, so thanks for the clarification.

it :lgtm: 
but please try to run sanity on this change before merge to dev.  It looks like internal change in the provisioner.
Can we use StorageClassName after this fix?

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/80#-:-KwGo8LaWTs0Z8C7o6uw:b-acm857)*

**Comment by midoblgsm** [comment]
After this fix I was successful to create a PVC with storageClassName and without the "storageClass" annotation, the provisioner picked it up and provisioned the PV and bound it to the PVC.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/80#-:-KwGqCUyB69JRiXEtD1P:b572atn)*

**Comment by shay-berman** [comment]
Mohamed, is this fix should works for all k8s version we plan to support - 1.5.6 &&  1.6   &&  1.7 ?
or this upgrade will work only for the latest version (i saw you pointed the external-storage for MASTER which is 1.8 I guess)?

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/80#-:-KwGudVg6BuSpCvQGM2E:b4fz2pi)*

**Comment by midoblgsm** [comment]
This should work with all versions that support the dynamic provisioning (starting from 1.5.4 I think)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/80#-:-KwGvJa92U5_IlC9jxSl:blnqpl6)*

**Comment by shay-berman** [comment]
ok great so 
:lgtm_strong: 

later on i will fix the acceptance tests to work with the new namespace feature, so when you will push it to dev the CI will give you indication about your merge.

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/80#-:-KwGxWecFj1zpQgg2mW0:bgo6cu7)*

**Comment by shay-berman** [comment]
I fixed the acceptance, and run it with the new storageclassName fix and it works good +1
please review https://github.com/IBM/ubiquity-k8s/pull/102

**Pull request merged**
