### PR TITLE
Fix/ub 1325 change logger not to show pid and goroutine

### PR DESCRIPTION
**Pull request by olgashtivelman**
In this PR I wanted to update the new logging to the following state:
in the ubiquity logger there we be shown  the go routine id (and the pid will be removed from the log) : because the ubiquity server always runs in the same pid so no need to show it in the log since it does not give us any more information.
in flex logger we will show the pid only (the go id routine will be removed) : since every flex request will always have the same go routine id there is not need to show both the request id and the go routine id.
in provisioner log we will neither show the go routine id nor the pid of the process : since as for the flex logger each request will always have the same go routine id. and also like the ubiqity server the provisioner will always run with the same pid.

link to ubiquity PR : https://github.com/IBM/ubiquity/pull/218

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/194)

### CODE REVIEW

**Comment by shay-berman** [comment]
@olgashtivelman please follow up my comment -> https://github.com/IBM/ubiquity/pull/218#issuecomment-399025148

**Comment by olgashtivelman** [comment]
@shay-berman please review the changes after out discussion

---

Review status: 0 of 7 files reviewed, all discussions resolved (waiting on @shay-berman)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/194#-:-LFwNpyc3CrRsx6XsY1L:ba5ypzg)*

**Comment by shay-berman** [comment]
Great thanks,   now we have one place to define the logger for flex and provisioner
please check my comments - small fixes to do
and its 
:lgtm: 

---

Review status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @olgashtivelman and @shay-berman)

---

*[cmd/flex/main/cli.go, line 46 at r4](https://reviewable.io/reviews/ibm/ubiquity-k8s/194#-LG-8jeM9emYqRJN2Z5r:-LG-8jeM9emYqRJN2Z5s:blx3obn) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f424553c6798e3d93f3c69f6a4999d223c7ff231/cmd/flex/main/cli.go#L46)):*
> ```Go
> )
> 
> var logger_params = logs.LoggerParams{ShowGoid: false, ShowPid : true}
> ```

i guess you forgot to remove this, right?

---

*[cmd/provisioner/main/main.go, line 53 at r4](https://reviewable.io/reviews/ibm/ubiquity-k8s/194#-LG-9SOV76gEUgJ4O0gv:-LG-9SOV76gEUgJ4O0gw:b-t4xqyo) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f424553c6798e3d93f3c69f6a4999d223c7ff231/cmd/provisioner/main/main.go#L53)):*
> ```Go
> 	}
> 
> 	//defer logs.InitStdoutLogger(logs.GetLogLevelFromString(ubiquityConfig.LogLevel), logs.LoggerParams{ShowGoid: false, ShowPid : false})()
> ```

please remove the line, no need to keep this comment

---

*[utils/logger_utils.go, line 17 at r4](https://reviewable.io/reviews/ibm/ubiquity-k8s/194#-LG-9zO64-tNmeXqjB5s:-LG-9zO64-tNmeXqjB5t:bhvw7tv) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f424553c6798e3d93f3c69f6a4999d223c7ff231/utils/logger_utils.go#L17)):*
> ```Go
> 
> func InitProvisionerLogger(ubiquityConfig resources.UbiquityPluginConfig) func(){
> 	deferFunction :=  logs.InitStdoutLogger(logs.GetLogLevelFromString(ubiquityConfig.LogLevel), logs.LoggerParams{ShowGoid: false, ShowPid : false})
> ```

just validate with you
we don't show the goid in provisioner because we will have different request ID each time, and its good enough for the logging, right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/194#-:-LG-AgvG7OioOi09XV4e:bpdida4)*

**Comment by olgashtivelman** [comment]
Review status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @shay-berman and @olgashtivelman)

---

*[cmd/flex/main/cli.go, line 46 at r4](https://reviewable.io/reviews/ibm/ubiquity-k8s/194#-LG-8jeM9emYqRJN2Z5r:-LG0REUMC4P0HL1ThZHV:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f424553c6798e3d93f3c69f6a4999d223c7ff231/cmd/flex/main/cli.go#L46)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

i guess you forgot to remove this, right?
</blockquote></details>

Done.

---

*[cmd/provisioner/main/main.go, line 53 at r4](https://reviewable.io/reviews/ibm/ubiquity-k8s/194#-LG-9SOV76gEUgJ4O0gv:-LG0RL216lbNG5hp57dl:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f424553c6798e3d93f3c69f6a4999d223c7ff231/cmd/provisioner/main/main.go#L53)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

please remove the line, no need to keep this comment
</blockquote></details>

Done.

---

*[utils/logger_utils.go, line 17 at r4](https://reviewable.io/reviews/ibm/ubiquity-k8s/194#-LG-9zO64-tNmeXqjB5s:-LG0RMkw2CFHjrhgEBju:b-jdgi) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f424553c6798e3d93f3c69f6a4999d223c7ff231/utils/logger_utils.go#L17)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

just validate with you
we don't show the goid in provisioner because we will have different request ID each time, and its good enough for the logging, right?
</blockquote></details>

yes,. since the request id and the go id are the same for the provisioner we will only want to show the request id. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/194)*

**Comment by olgashtivelman** [comment]
Review status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @shay-berman)

---

*[utils/logger_utils.go, line 17 at r4](https://reviewable.io/reviews/ibm/ubiquity-k8s/194#-LG-9zO64-tNmeXqjB5s:-LG0Rf5Y8P-hM2NmIvnn:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f424553c6798e3d93f3c69f6a4999d223c7ff231/utils/logger_utils.go#L17)):*
<details><summary><i>Previously, olgashtivelman wrote…</i></summary><blockquote>

yes,. since the request id and the go id are the same for the provisioner we will only want to show the request id. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/194)*

**Comment by olgashtivelman** [comment]
@shay-berman please review the comments so that i can merge the changes

---

Review status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @shay-berman)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/194#-:-LG0TwPzCtgXUilTuD9k:b-h1abhn)*

**Comment by shay-berman** [comment]
:lgtm:

---

Reviewed 3 of 7 files at r3, 1 of 3 files at r4, 2 of 3 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/194#-:-LG0e7cR3cIeyeNWQEjc:bnfp4nl)*

**Pull request merged**
