### PR TITLE
Fix/ub 624 flex should not write log into flex driver director

### PR DESCRIPTION
**Pull request by hfeish**
Handle flex logrotate internal
    configurable for FLEX-LOG-DIR in ubiquity-configmap.yml and ubiquity_installer.conf, default is /var/log, customer need to make sure Flex-Log-dir exist in the minors
    configurable for FLEX-LOG-ROTATE-MAXSIZE in ubiquity-configmap.yml, default is 50MB

How to test:
    1. check the default log path: /var/log(exist in all flex pods, and nodes), logs will rotate if > 50 MB, will keep 5 compressed log file
    2. can change log path to example /var/log/ubiquity in ubiquity_install.conf and configmap, need to make sure this path existed(in all nodes, also for controller-manager-pod) before install
    3. can change log rotate size from 50MB to others in ubiquity-configmap
    4. flex binary will create the log dir (ex: /var/log/ubiquity) if it not exist
    5. flex logs not sit on k8s plugin directory

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/166)

### CODE REVIEW

**Comment by shay-berman** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[Dockerfile.Flex, line 11 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/166#-L58OUABMe2w-VelXeqU:-L58OUABMe2w-VelXeqV:b5pbgef) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f8457b8784d32426a2fa9668ff48eaba810dc331/Dockerfile.Flex#L11)):*
> ```
> FROM alpine:latest
> RUN apk --no-cache add ca-certificates
> RUN apk --update add logrotate
> ```

Fei, don't forget to remove also the logrotate apk add, since we don't need it any more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/166)*

**Comment by hfeish** [comment]
remove also the logrotate apk add

**Comment by shay-berman** [comment]
Review status: 0 of 9 files reviewed at latest revision, 12 unresolved discussions, some commit checks broke.

---

*[deploy/k8s_deployments/setup_flex.sh, line 9 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/166#-L6QgPONqF4N5cTisnrV:-L6QgPONqF4N5cTisnrW:b-94cy47) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f8457b8784d32426a2fa9668ff48eaba810dc331/deploy/k8s_deployments/setup_flex.sh#L9)):*
> ```Shell
> #    /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ibm~ubiquity-k8s-flex
> # 2. Run tail -f on the flex log file, so it will be visible via kubectl logs <flex Pod>
> # 3. Start infinite loop with logrotate every 24 hours on the host flex log file
> ```

bring this line back, because we still do infinit loop, but now only for tailing the log

---

*[deploy/k8s_deployments/setup_flex.sh, line 159 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/166#-L6QhTwF9RCk_xzLIrtN:-L6QhTwF9RCk_xzLIrtO:brxkhkw) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/deploy/k8s_deployments/setup_flex.sh#L159)):*
> ```Shell
> echo "Running in the background tail -F <flex log>, so the log will be visible though kubectl logs <flex POD>"
> echo "[`date`] Start to run in background #>"
> echo "tail -F ${FLEX_LOG_DIR}/ubiquity-k8s-flex.log"
> ```

please don't hardcoded the flex log file, just use   ${DRIVER}

---

*[deploy/k8s_deployments/setup_flex.sh, line 161 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/166#-L6Qhc8M8v0osbqVToYV:-L6Qhc8M8v0osbqVToYW:br9hgq0) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/deploy/k8s_deployments/setup_flex.sh#L161)):*
> ```Shell
> echo "tail -F ${FLEX_LOG_DIR}/ubiquity-k8s-flex.log"
> echo "-----------------------------------------------"
> tail -F ${FLEX_LOG_DIR}/ubiquity-k8s-flex.log &
> ```

same here,, just use   ${DRIVER} instead of ubiqutiy-k8s-flex.log

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 32 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/166#-L6QiTe-c-tASnJ8WgF6:-L6QiTe-c-tASnJ8WgF7:bh0y8ah) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L32)):*
> ```YAML
>    # The following keys are used by ubiquity, ubiquity-k8s-provisioner deployments, And ubiquity-k8s-flex daemon-set
>    # ----------------------------------------------------------------------------------------------------------------------------
>    # Flex log path. Allow to configure it, just make sure the the new path exist on all the minons and update the hostpath in the daemonset
> ```

"daemonset" -> "Flex daemonset"

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 33 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/166#-L6QjOTECPD1vDfv5Db4:-L6QjOTECPD1vDfv5Db5:b-gzgnpz) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L33)):*
> ```YAML
>    # ----------------------------------------------------------------------------------------------------------------------------
>    # Flex log path. Allow to configure it, just make sure the the new path exist on all the minons and update the hostpath in the daemonset
>    FLEX_LOG_DIR: "FLEX_LOG_DIR_VALUE"
> ```

keep the convention,  the key name should be with - and not with _.  please fix it FLEX-LOG-DIR

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 35 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/166#-L6QiDLz416_WXSjHBDk:-L6QiDLz416_WXSjHBDl:b-5ydaav) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L35)):*
> ```YAML
>    FLEX_LOG_DIR: "FLEX_LOG_DIR_VALUE"
> 
>    #Maxlog size(MB) for rotate
> ```

missing space after "#" sign

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 36 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/166#-L6Qjbi4u_Xy_uh8cGkH:-L6Qjbi4u_Xy_uh8cGkI:beon394) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L36)):*
> ```YAML
> 
>    #Maxlog size(MB) for rotate
>    FLEX_LOG_ROTATE_MAXSIZE: "50"
> ```

FLEX-LOG-ROTATE-MAXSIZE

also please make sure you update Dima about these new variables so he will update the UG according.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_installer.conf, line 48 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/166#-L6QimmctmElAFEW5rUu:-L6QimmctmElAFEW5rUv:b-pj8f7t) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_installer.conf#L48)):*
> ```
> # Parameters in ubiquity-configmap.yml that impact on "ubiquity" and "ubiquity-k8s-provisioner" deployments, And "ubiquity-k8s-flex" daemonset
> #-----------------------------------------------------------------
> # Flex log path. Allow to configure it, just make sure the the new path exist on all the minons and update the hostpath in the daemonset
> ```

# Flex log directory. if you change the default, then make the new path exist on all the nodes and update the Flex daemonset hostpath according.

Note: validate string with Dima

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-k8s-flex-daemonset.yml, line 39 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/166#-L6QkiX60yfSAPVFWpz2:-L6QkiX60yfSAPVFWpz3:bofklo4) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-k8s-flex-daemonset.yml#L39)):*
> ```YAML
>               configMapKeyRef:
>                 name: ubiquity-configmap
>                 key: FLEX_LOG_DIR
> ```

don't forget to change the key to FLEX-LOG-DIR  also below

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-k8s-flex-daemonset.yml, line 104 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/166#-L6Qkw3uqxuJNy0z62ce:-L6Qkw3uqxuJNy0z62cf:bj9zvmq) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-k8s-flex-daemonset.yml#L104)):*
> ```YAML
>       - name: flex-log-dir
>         hostPath:
>           path: FLEX_LOG_DIR_VALUE  # This directory must exist on the host
> ```

append to the note :  if not the flex log will not be persistent and the flex pod will not be able to tail the log.

---

*[utils/utils.go, line 14 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/166#-L6QlEppPVffzYNbAJbY:-L6QlEppPVffzYNbAJbZ:b-6lwhrb) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/utils/utils.go#L14)):*
> ```Go
> 	config := resources.UbiquityPluginConfig{}
> 	config.LogLevel = os.Getenv("LOG_LEVEL")
> 	LogRotateMaxSize, err := strconv.Atoi(os.Getenv("FLEX_LOG_ROTATE_MAXSIZE"))
> ```

BUG
you should have a default in case the variable is not define.
its not enough to count on the default in the flex init script

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/166)*

**Comment by hfeish** [comment]
Review status: 0 of 9 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[deploy/k8s_deployments/setup_flex.sh, line 9 at r2](https://beta.reviewable.io/reviews/ibm/ubiquity-k8s/166#-L6QgPONqF4N5cTisnrV:-L6URUGB3G_2Bdyytntv:bh4dj0a) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f8457b8784d32426a2fa9668ff48eaba810dc331/deploy/k8s_deployments/setup_flex.sh#L9)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

bring this line back, because we still do infinit loop, but now only for tailing the log
</blockquote></details>

bring back

---

*[deploy/k8s_deployments/setup_flex.sh, line 159 at r2](https://beta.reviewable.io/reviews/ibm/ubiquity-k8s/166#-L6QhTwF9RCk_xzLIrtN:-L6URlIp2C_z5x6adKQD:bb6un1j) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/deploy/k8s_deployments/setup_flex.sh#L159)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

please don't hardcoded the flex log file, just use   ${DRIVER}
</blockquote></details>

Done

---

*[deploy/k8s_deployments/setup_flex.sh, line 161 at r2](https://beta.reviewable.io/reviews/ibm/ubiquity-k8s/166#-L6Qhc8M8v0osbqVToYV:-L6URsPU33iPptzc7YsG:bb6un1j) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/deploy/k8s_deployments/setup_flex.sh#L161)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

same here,, just use   ${DRIVER} instead of ubiqutiy-k8s-flex.log
</blockquote></details>

Done

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 32 at r2](https://beta.reviewable.io/reviews/ibm/ubiquity-k8s/166#-L6QiTe-c-tASnJ8WgF6:-L6USM6j7nM7qczW2C7L:bb6un1j) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L32)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

"daemonset" -> "Flex daemonset"
</blockquote></details>

Done

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 33 at r2](https://beta.reviewable.io/reviews/ibm/ubiquity-k8s/166#-L6QjOTECPD1vDfv5Db4:-L6USWMY8me_k2zi0pkA:bb6un1j) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L33)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

keep the convention,  the key name should be with - and not with _.  please fix it FLEX-LOG-DIR
</blockquote></details>

Done

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 35 at r2](https://beta.reviewable.io/reviews/ibm/ubiquity-k8s/166#-L6QiDLz416_WXSjHBDk:-L6USdGTE9X_G-nmJMFR:bb6un1j) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L35)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

missing space after "#" sign
</blockquote></details>

Done

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 36 at r2](https://beta.reviewable.io/reviews/ibm/ubiquity-k8s/166#-L6Qjbi4u_Xy_uh8cGkH:-L6USfMl5msGmTkHhrDS:bxpkd88) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L36)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

FLEX-LOG-ROTATE-MAXSIZE

also please make sure you update Dima about these new variables so he will update the UG according.
</blockquote></details>

Done, will info Dima

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ibm/ubiquity-k8s/166)*

**Comment by hfeish** [comment]
Review status: 0 of 9 files reviewed at latest revision, 12 unresolved discussions, some commit checks broke.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_installer.conf, line 48 at r2](https://beta.reviewable.io/reviews/ibm/ubiquity-k8s/166#-L6QimmctmElAFEW5rUu:-L6UU_807k5pB2srANG5:bb6un1j) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_installer.conf#L48)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

# Flex log directory. if you change the default, then make the new path exist on all the nodes and update the Flex daemonset hostpath according.

Note: validate string with Dima
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ibm/ubiquity-k8s/166)*

**Comment by shay-berman** [comment]
@hfeish  please do NOT merge to dev yet.  We may postponed this fix to the next Ubiquity release.

**Comment by shay-berman** [comment]
I reviewed it now,   please apply the comments and then you can merge it.

---

Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Dockerfile.Flex, line 11 at r1](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-L58OUABMe2w-VelXeqU:-LBthgyjDXZzrTBvsTtq:b-p50jbl) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f8457b8784d32426a2fa9668ff48eaba810dc331/Dockerfile.Flex#L11)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

Fei, don't forget to remove also the logrotate apk add, since we don't need it any more.
</blockquote></details>

ok i see you removed it

---

*[glide.yaml, line 12 at r3](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-LBthmAB8x-7PMKoZavR:-LBthmACDgCrRSpQqq8d:b-2oa82r) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/2c9f905a04d573083e88e5f72b3f591af6e8988e/glide.yaml#L12)):*
> ```YAML
>   - lib
> - package: github.com/IBM/ubiquity
>   version: fix/UB-624_Flex_should_not_write_log_into_flex_driver_directory
> ```

please don't merge this version to dev.

---

*[deploy/k8s_deployments/setup_flex.sh, line 82 at r3](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-LBtig8RCFTAX7tEnnEu:-LBtig8RCFTAX7tEnnEv:b-wrlgo5) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/2c9f905a04d573083e88e5f72b3f591af6e8988e/deploy/k8s_deployments/setup_flex.sh#L82)):*
> ```Shell
> }
> 
> function create_flex_log_dir()
> ```

is this needed?  does the flex it self create the dir if not exist?

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-k8s-flex-daemonset.yml, line 39 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-L6QkiX60yfSAPVFWpz2:-LBtlsZk8rnuCq-4WWOJ:b3egpbq) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-k8s-flex-daemonset.yml#L39)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

don't forget to change the key to FLEX-LOG-DIR  also below
</blockquote></details>

thanks for fixing

---

*[utils/utils.go, line 14 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-L6QlEppPVffzYNbAJbY:-LBtnCTqAm5wzb32f-rh:b-s4m3b0) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/utils/utils.go#L14)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

BUG
you should have a default in case the variable is not define.
its not enough to count on the default in the flex init script
</blockquote></details>

ok 
I see that you fixed that
please try to add UT for it as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-:-LBtnKjh3W0TFxTDojaa:b-v6nn5l)*

**Comment by hfeish** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[glide.yaml, line 12 at r3](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-LBthmAB8x-7PMKoZavR:-LCgmJvK4SUVd-6_044V:b-fze4j8) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/2c9f905a04d573083e88e5f72b3f591af6e8988e/glide.yaml#L12)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

please don't merge this version to dev.
</blockquote></details>

Sure, I will change it to dev while merging to dev

---

*[deploy/k8s_deployments/setup_flex.sh, line 82 at r3](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-LBtig8RCFTAX7tEnnEu:-LCh1p9hCAbd4aeRR50k:b-wxgc16) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/2c9f905a04d573083e88e5f72b3f591af6e8988e/deploy/k8s_deployments/setup_flex.sh#L82)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

is this needed?  does the flex it self create the dir if not exist?
</blockquote></details>

You're right, we don't need this

---

*[utils/utils.go, line 14 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-L6QlEppPVffzYNbAJbY:-LCh1tN38iMahlJRfCCa:b-t9zmun) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/utils/utils.go#L14)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

ok 
I see that you fixed that
please try to add UT for it as well.
</blockquote></details>

Any suggestion here? you mean we need to add UT for "func LoadConfig"?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/166)*

**Comment by shay-berman** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[utils/utils.go, line 14 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-L6QlEppPVffzYNbAJbY:-LChcWul25VvY01GGNm8:b-3fmt9d) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/utils/utils.go#L14)):*
<details><summary><i>Previously, hfeish (Fei Huang) wrote…</i></summary><blockquote>

Any suggestion here? you mean we need to add UT for "func LoadConfig"?
</blockquote></details>

you don't need to mock something here
just create UT that call this function while you change the envs before calling it, and make sure it do the Loadconfiguration well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/166)*

**Comment by hfeish** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[utils/utils.go, line 14 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-L6QlEppPVffzYNbAJbY:-LD-a8-aAotFAhmoN0lb:bl0ijbw) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/6b03cc9ffcf256921bbe7329305df697e5dee04f/utils/utils.go#L14)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

you don't need to mock something here
just create UT that call this function while you change the envs before calling it, and make sure it do the Loadconfiguration well.
</blockquote></details>

Add utils_test.go for this UT

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/166)*

**Comment by shay-berman** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[utils/utils_test.go, line 4 at r4](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-LD1xkDuA4SrnPWmZgbx:-LD1xkDuA4SrnPWmZgby:brw7c3v) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/68e72145d82c57a508df85031bd4780d2b56a82b/utils/utils_test.go#L4)):*
> ```Go
> 
> import (
> 	"testing"
> ```

why you are not doing it with Ginkgo? like we do for all the UTs?  
with Describe \ BeforeEach \ Context and then It() testing?   

any reason why you choose to do it different?

its a bit hard to understand what you want to test in tests1 and tests1

---

*[utils/utils_test.go, line 92 at r4](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-LD1yfeT4E6hkkQDIcKm:-LD1yfeT4E6hkkQDIcKn:b-senew7) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/68e72145d82c57a508df85031bd4780d2b56a82b/utils/utils_test.go#L92)):*
> ```Go
> 	ubiquityConfig, err := k8sutils.LoadConfig()
> 	if err != nil {
> 		fmt.Println("LoadConfig failed: ",err)
> ```

why you just print error?  don't you need to fail here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/166)*

**Comment by hfeish** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[utils/utils_test.go, line 4 at r4](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-LD1xkDuA4SrnPWmZgbx:-LD573_1Ceu2bG1y_-pn:bucs1pv) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/68e72145d82c57a508df85031bd4780d2b56a82b/utils/utils_test.go#L4)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

why you are not doing it with Ginkgo? like we do for all the UTs?  
with Describe \ BeforeEach \ Context and then It() testing?   

any reason why you choose to do it different?

its a bit hard to understand what you want to test in tests1 and tests1
</blockquote></details>

I use it because we need a lot data to set in the env to test, so I use the data table drive test.
In test1, set the correct env value and after LoadConfig it will get the same value
In test2, since in LoadConfig FLEX_LOG_ROTATE_MAXSIZE and SCBE_SKIP_RESCAN_ISCSI have default value, so test it here.

---

*[utils/utils_test.go, line 92 at r4](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-LD1yfeT4E6hkkQDIcKm:-LD58TsL7utMkWu71EcN:b-otiff1) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/68e72145d82c57a508df85031bd4780d2b56a82b/utils/utils_test.go#L92)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

why you just print error?  don't you need to fail here?
</blockquote></details>

Add t.Fail() here

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/166)*

**Comment by shay-berman** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[utils/utils_test.go, line 4 at r4](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-LD1xkDuA4SrnPWmZgbx:-LD5W52c8zzgg-KKPEUc:bp8swvl) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/68e72145d82c57a508df85031bd4780d2b56a82b/utils/utils_test.go#L4)):*
<details><summary><i>Previously, hfeish (Fei Huang) wrote…</i></summary><blockquote>

I use it because we need a lot data to set in the env to test, so I use the data table drive test.
In test1, set the correct env value and after LoadConfig it will get the same value
In test2, since in LoadConfig FLEX_LOG_ROTATE_MAXSIZE and SCBE_SKIP_RESCAN_ISCSI have default value, so test it here.
</blockquote></details>

but u can still use data set in ginkgo test framework   and the make it more standard lile all other test structure   and then u can use assert insted of doing if else stuff.

so just wonder if there is real reason u used testing instead of ginkgo?
btw r u sure that by running scripts/run_unit script it will trigger this test?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/166)*

**Comment by hfeish** [comment]
Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[utils/utils_test.go, line 4 at r4](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-LD1xkDuA4SrnPWmZgbx:-LD5v8-WAtZQ_07BjN-k:bt342cg) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/68e72145d82c57a508df85031bd4780d2b56a82b/utils/utils_test.go#L4)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

but u can still use data set in ginkgo test framework   and the make it more standard lile all other test structure   and then u can use assert insted of doing if else stuff.

so just wonder if there is real reason u used testing instead of ginkgo?
btw r u sure that by running scripts/run_unit script it will trigger this test?
</blockquote></details>

Yes, you are right, change it to ginkgo, please review

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/166)*

**Comment by shay-berman** [comment]
Review my last comments 
anyway it :lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[glide.yaml, line 13 at r5](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-LD6wQxAECayWPaB75-K:-LD6wQxAECayWPaB75-L:b-2ppqdp) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/99632ba22fbda78a2500e359bdc71973fc4f1931/glide.yaml#L13)):*
> ```YAML
> - package: github.com/IBM/ubiquity
>   version: fix/UB-624_Flex_should_not_write_log_into_flex_driver_directory
>   subpackages:
> ```

make sure to set it to dev branch before merge to dev.

---

*[utils/utils_test.go, line 4 at r4](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-LD1xkDuA4SrnPWmZgbx:-LD5vjQs9Tj3aSXrew1Q:brapn00) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/68e72145d82c57a508df85031bd4780d2b56a82b/utils/utils_test.go#L4)):*
<details><summary><i>Previously, hfeish (Fei Huang) wrote…</i></summary><blockquote>

Yes, you are right, change it to ginkgo, please review
</blockquote></details>

much better, thanks!

small improvement (its not a must) - but I would move the tests1 var into the first It and tests2 into second It.  
but anyway its good enough.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/166#-:-LD6wX4P1M5S3LcdqDnB:bvey917)*

**Pull request merged**
