### PR TITLE
Update to k8s 1.9 in glide

### PR DESCRIPTION
**Pull request by beckmani**
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/192)

### CODE REVIEW

**Comment by shay-berman** [comment]
isaac, since u change the dependencies versions  you must update it also in the internal wiki page of the release (for legal aspects)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[glide.yaml, line 33 at r1](https://reviewable.io/reviews/ibm/ubiquity-k8s/192#-LEFUMjo8bc9wvFBmq3F:-LEFUMjp4b_hA0OBe8z2:bf7w4og) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/12328a481bd139001643120f9b6efcfbdce969e2/glide.yaml#L33)):*
> ```YAML
>   - pkg/watch
> - package: k8s.io/client-go
>   version: release-6.0
> ```

is this the lateat?     
the PR name doesnot say anything about this change
so please add description to the PR with details about this change.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/192#-:-LEFUjg4-qsF5sggfuOX:bb95npq)*

**Comment by beckmani** [comment]
*[glide.yaml, line 33 at r1](https://reviewable.io/reviews/ibm/ubiquity-k8s/192#-LEFUMjo8bc9wvFBmq3F:-LEO2qmd8x-ciqMQ5RTX:b-metbnr) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/12328a481bd139001643120f9b6efcfbdce969e2/glide.yaml#L33)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

is this the lateat?     
the PR name doesnot say anything about this change
so please add description to the PR with details about this change.
</blockquote></details>

See "State of the published repositories" in https://kubernetes.io/blog/2018/01/introducing-client-go-version-6/

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/192)*

**Comment by shay-berman** [comment]
so please check if it pass UT and staging.   if so then it can be merged

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/192#-:-LEOoCqmARiRHgG2ouej:bg2rppx)*

**Comment by beckmani** [comment]
Unittests completed successfully.
Also Staging completed with no errors: https://stg-jenkins.xiv.ibm.com/job/CSS/job/Product/job/SCB/job/Ubiquity/job/Ubiquity_k8s_v1.8.4_xavi_A9000_ubuntu_iscsi_multijob/120/

---







*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/192#-:-LEhYt6cBmaWH_fE_fAM:b-fjj4jb)*

**Comment by shay-berman** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed, all discussions resolved (waiting on @shay-berman)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/192#-:-LFRTN6pAIaO2dx4ZSku:bnfp4nl)*

**Pull request merged**
