### PR TITLE
Sequential unmount ops by adding lock (unmountFlock) to the Flex controller Unmount action

### PR DESCRIPTION
**Pull request by shay-berman**
This PR should reduce the risk of having bad WWN show up in the multipath -ll.

**How to reduce the risk**
by preventing multiple DELETE pods to run cuncurently and do multipath removal \ storage unmap and rescans at the same time. This senaio has a potential race when deleting mpath device while at the same time a parallel delete request may run rescan and return back the deleted mpath device. This kind of race may lead for some multipath bad behavior where a mpath device presented with wrong WWN in multipath -ll (look likes a multipathd issue).

Note: this lock may have performance impact due to serialize the delete POD operations. but its better to have performance degradation rather then risking multipathing bad WWN.

**How to test**
Run concurrent DELETE pod at the same time (like the acceptance test do), and make sure

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/154)

### CODE REVIEW

**Comment by alonm** [comment]
*[glide.yaml, line 49 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154#-L-yW-2h-csH00Rla4Aq:-L-yW-2h-csH00Rla4Ar:b-4kw0p7) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/abef35172003475c1f2a4f8fab079de99a252355/glide.yaml#L49)):*
> ```YAML
>   - pkg/util/goroutinemap
>   - pkg/util/version
> - package: github.com/nightlyone/lockfile
> ```

already approved in the other glide file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154)*

**Comment by ranhrl** [comment]
The locking should be global for all the actions that do rescan/multipath operations as attach/mount may interfere with umount/detach operations. 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154#-:-L-zMLrMLl5xSvkrKQ23:b-vul0l9)*

**Comment by shay-berman** [comment]
cannot do filelock between [attach] and [unmount+detach] because the attach is done by the master(while the umount+detach done on the worker node). Note remember that rescan operation are already serialized by rescanLock.

I can expend the umountLock also to prevent the mount part to run in parallel. But lets first check this unmountLock.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154#-:-L01Eysi6sGxEKxdFtA5:b-8wens2)*

**Comment by shay-berman** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[glide.yaml, line 49 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154#-L-yW-2h-csH00Rla4Aq:-L095U4TVTWtYGA06TNB:b9fbohf) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/abef35172003475c1f2a4f8fab079de99a252355/glide.yaml#L49)):*
<details><summary><i>Previously, alonm wrote…</i></summary><blockquote>

already approved in the other glide file
</blockquote></details>

sure 10x

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154)*

**Comment by tzurE** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[controller/controller.go, line 55 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154#-L09FLP6kyTYyeog0wvf:-L09FLP6kyTYyeog0wvg:bpg6wse) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/abef35172003475c1f2a4f8fab079de99a252355/controller/controller.go#L55)):*
> ```Go
> 	unmountFlock, err := lockfile.New(filepath.Join(os.TempDir(), "ubiquity.unmount.lock"))
> 	if err != nil {
> 		panic(err)
> ```

Is panic enough? Shouldn't we maybe add something more informative? 

---

*[controller/controller.go, line 299 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154#-L09G3oChJaYVlRwZGdN:-L09G3oDsG_dYtZAp3Vl:b-ku0kvb) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/abef35172003475c1f2a4f8fab079de99a252355/controller/controller.go#L299)):*
> ```Go
> 		}
> 		c.logger.Debug("unmountFlock.TryLock failed", logs.Args{{"error", err}})
> 		time.Sleep(time.Duration(100*time.Millisecond))
> ```

This is for the busy wait? keep checking every 100 milli? maybe you should increase it.

And we need to implement something else. 
https://josephmate.wordpress.com/2016/02/04/how-to-avoid-busy-waiting/
We should implement monitor or channeling like here:
https://www.golang-book.com/books/intro/10
Where we can actually insert every waiting thread to a list and wake them only when they need to work. we save a lot of CPU cycles on waiting threads and all. 
But this is for next release...maybe.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154)*

**Comment by shay-berman** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[controller/controller.go, line 55 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154#-L09FLP6kyTYyeog0wvf:-L09JMVtrbZjNaBe9hqL:b-8jg2dl) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/abef35172003475c1f2a4f8fab079de99a252355/controller/controller.go#L55)):*
<details><summary><i>Previously, tzurE wrote…</i></summary><blockquote>

Is panic enough? Shouldn't we maybe add something more informative? 
</blockquote></details>

the error comes from the lock its good enough. try to minimize changes now

---

*[controller/controller.go, line 299 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154#-L09G3oChJaYVlRwZGdN:-L09JzqFHk4zeESA4mQb:b-ombove) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/abef35172003475c1f2a4f8fab079de99a252355/controller/controller.go#L299)):*
<details><summary><i>Previously, tzurE wrote…</i></summary><blockquote>

This is for the busy wait? keep checking every 100 milli? maybe you should increase it.

And we need to implement something else. 
https://josephmate.wordpress.com/2016/02/04/how-to-avoid-busy-waiting/
We should implement monitor or channeling like here:
https://www.golang-book.com/books/intro/10
Where we can actually insert every waiting thread to a list and wake them only when they need to work. we save a lot of CPU cycles on waiting threads and all. 
But this is for next release...maybe.
</blockquote></details>

Try to minimize changes now. (will not do Exponential Backoff)
Ran \ Alon, what do you say about 100 msec?   we can expend it to 500 msec to reduce cycles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154)*

**Comment by tzurE** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[controller/controller.go, line 299 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154#-L09G3oChJaYVlRwZGdN:-L09QzO5FJmAsyVb-4GP:b5umxyp) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/abef35172003475c1f2a4f8fab079de99a252355/controller/controller.go#L299)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

Try to minimize changes now. (will not do Exponential Backoff)
Ran \ Alon, what do you say about 100 msec?   we can expend it to 500 msec to reduce cycles.

</blockquote></details>

I believe it's best to do it 1000 ms.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154)*

**Comment by ranhrl** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/154#-:-L09btqbUnMiAWs8luRS:bnfp4nl)*

**Comment by shay-berman** [comment]
This PR passed acceptance tests night runs on A9000 and V9000 with success.
looks like the new locking preventing for having faulty mpath devices.
We decided to merge it to dev.

There still 2 things to improve : (1) to make sure sg_inq runs on all mpath devices (2) don't work on faulty devices.  A dedicated tickets will be opened to handle these 2 things (none blocking issues)

**Pull request merged**
