### PR TITLE
UB-1538 : Feature/ubiqutiy service account

### PR DESCRIPTION
**Pull request by shay-berman**
Simplify ubiquity deployment and also provide better security inside k8s deployment by setting the right RBAC for the ubiqutiy application.

Details:
1. This PR adding new objects: ubiqutiy service account, clusterRoles and clusterRolesBinding.
2. Adding new ymls for these new k8s objects into the installer yml directory.
3. ubiqutiy_installer.sh should install these objects in the right order (after namespace creation, it should install serviceaccount -> clusterRoles -> clusterRolesBinding)
4. ubiqutiy_uninstall.sh should install these objects in the right order (opposite order of the installer)

**Note:** 
The PR is not ready yet. Follow up items to implement:

0. Provisioner code to get the k8s client config from the new ubiquity service account - currently it took it from /tmp/k8sconfig/config
1. Remove -k from the installer
2. Test the installer\uninstall and cli status
3. Collect logs also from the new objects
4. Currently its only integrated to the installer, but later on we should add it also to the new Helm chart as well.
5. Add section of how to test the PR

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/215)

### CODE REVIEW

**Comment by matt-levan** [comment]
:lgtm:

**Comment by shay-berman** [comment]
@matt-levan , can you please verify that it is working ok in your latest ICP version?

**Comment by matt-levan** [comment]
Tested with IBM Cloud Private 3.1.0 and ubiquity images 1.2.0.

**Comment by gerosch** [comment]
Replacing the -k option of the Ubiquity installer and adding a service account, cluster role, and cluster role binding for Ubiquity is the right way to go. The prometheus Helm chart at [https://github.com/helm/charts/tree/master/stable/prometheus] may have good templates for these to start with.

**Comment by shay-berman** [comment]
thanks @gerosch  and @matt-levan  for your inputs, appreciate that.

**Pull request merged**
