### PR TITLE
UB-1099: add go_id:request_id to flex and provisioner logs

### PR DESCRIPTION
**Pull request by olgashtivelman**
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/191)

### CODE REVIEW

**Comment by olgashtivelman** [comment]
the ubiquity review link.
https://github.com/IBM/ubiquity/pull/215

this is the change to add reqeuest_id and go routine id to the ubiquity + flex + provisioner logs so that we can follow a single request through out the product. (and also be able to identify which logs belong to which request in a multi-threaded server like ubiquity.)

**Comment by shay-berman** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[cmd/flex/main/cli.go, line 95 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-LEdbK8W0UPQ5wvQ9LDz:-LEdbK8W0UPQ5wvQ9LE-:bdc2wcz) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e748541eb6f00cbdd12ec5f2f7cda22b92dc2420/cmd/flex/main/cli.go#L95)):*
> ```Go
> 
> 	requestContext := k8sutils.GetNewRequestContext()
> 	fmt.Sprintf("Starting attach command [%s]", k8sutils.GetContextRequestString(requestContext))
> ```

wait this is not good
why you added fmt.sprintf which will go to the STDOUT?   it may confuse controller manager which expect a specific response in STDOUT.
you should use the logger to print debug\info logging.

---

*[cmd/flex/main/cli.go, line 147 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-LEdbeQk5nROIem3Zc2T:-LEdbeQk5nROIem3Zc2U:b-fv94nk) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e748541eb6f00cbdd12ec5f2f7cda22b92dc2420/cmd/flex/main/cli.go#L147)):*
> ```Go
> 
> 	attachResponse := controller.Attach(attachRequest)
> 	fmt.Sprintf("Finishing attach command [%s]", k8sutils.GetContextRequestString(requestContext))
> ```

same, please use the logger instead STDOUT

---

*[cmd/flex/main/cli.go, line 159 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-LEdbh9vCzqdTGH2HXMV:-LEdbh9vCzqdTGH2HXMW:bmeg3yy) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e748541eb6f00cbdd12ec5f2f7cda22b92dc2420/cmd/flex/main/cli.go#L159)):*
> ```Go
> func (wfa *WaitForAttachCommand) Execute(args []string) error {
> 	requestContext := k8sutils.GetNewRequestContext()
> 	fmt.Sprintf("Starting WaitForAttachCommand command [%s]", k8sutils.GetContextRequestString(requestContext))
> ```

same, please use the logger instead STDOUT

---

*[cmd/flex/main/cli.go, line 190 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-LEdbjJrDuZaB1GdYe49:-LEdbjJrDuZaB1GdYe4A:bmeg3yy) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e748541eb6f00cbdd12ec5f2f7cda22b92dc2420/cmd/flex/main/cli.go#L190)):*
> ```Go
> 	waitForAttachRequest := k8sresources.FlexVolumeWaitForAttachRequest{Name: args[0], Opts: opts, Context: requestContext}
> 	response := controller.WaitForAttach(waitForAttachRequest)
> 	fmt.Sprintf("Finished WaitForAttachCommand command [%s]", k8sutils.GetContextRequestString(requestContext))
> ```

same, please use the logger instead STDOUT

---

*[cmd/flex/main/cli.go, line 202 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-LEdboCxCZxe_4z9UHKa:-LEdboCy1M0k2e9mHYgq:bmeg3yy) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e748541eb6f00cbdd12ec5f2f7cda22b92dc2420/cmd/flex/main/cli.go#L202)):*
> ```Go
> func (d *IsAttachedCommand) Execute(args []string) error {
> 	requestContext := k8sutils.GetNewRequestContext()
> 	fmt.Sprintf("Starting IsAttachedCommand command [%s]", k8sutils.GetContextRequestString(requestContext))
> ```

same, please use the logger instead STDOUT

---

*[cmd/flex/main/cli.go, line 232 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-LEdbp5R3jVdE6060nCo:-LEdbp5R3jVdE6060nCp:bmeg3yy) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e748541eb6f00cbdd12ec5f2f7cda22b92dc2420/cmd/flex/main/cli.go#L232)):*
> ```Go
> 	isAttachedRequest := k8sresources.FlexVolumeIsAttachedRequest{Opts: opts, Host: args[1], Context: requestContext}
> 	response := controller.IsAttached(isAttachedRequest)
> 	fmt.Sprintf("Finished IsAttachedCommand command [%s]", k8sutils.GetContextRequestString(requestContext))
> ```

same, please use the logger instead STDOUT

---

*[cmd/flex/main/cli.go, line 245 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-LEdbpwk6w0F781MnMsR:-LEdbpwk6w0F781MnMsS:bmeg3yy) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e748541eb6f00cbdd12ec5f2f7cda22b92dc2420/cmd/flex/main/cli.go#L245)):*
> ```Go
> func (d *DetachCommand) Execute(args []string) error {
> 	requestContext := k8sutils.GetNewRequestContext()
> 	fmt.Sprintf("Starting DetachCommand command [%s]", k8sutils.GetContextRequestString(requestContext))
> ```

same, please use the logger instead STDOUT

---

*[cmd/flex/main/cli.go, line 281 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-LEdbr1jB4vzqhk11T_H:-LEdbr1jB4vzqhk11T_I:bmeg3yy) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e748541eb6f00cbdd12ec5f2f7cda22b92dc2420/cmd/flex/main/cli.go#L281)):*
> ```Go
> 	detachRequest := k8sresources.FlexVolumeDetachRequest{Name: mountDevice, Host: hostname, Version: version, Context: requestContext}
> 	detachResponse := controller.Detach(detachRequest)
> 	fmt.Sprintf("Finished DetachCommand command [%s]", k8sutils.GetContextRequestString(requestContext))
> ```

same, please use the logger instead STDOUT

---

*[cmd/flex/main/cli.go, line 293 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-LEdc97Z3N5ZtCuEiFPx:-LEdc97Z3N5ZtCuEiFPy:b-jl01sa) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e748541eb6f00cbdd12ec5f2f7cda22b92dc2420/cmd/flex/main/cli.go#L293)):*
> ```Go
> func (d *MountDeviceCommand) Execute(args []string) error {
> 	requestContext := k8sutils.GetNewRequestContext()
> 	fmt.Sprintf("Starting MountDeviceCommand command [%s]", k8sutils.GetContextRequestString(requestContext))
> ```

same and all the relevant below as well

---

*[utils/utils.go, line 59 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-LEdejWlEuQNeV2zoI9O:-LEdejWlEuQNeV2zoI9P:b-5bvdok) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e748541eb6f00cbdd12ec5f2f7cda22b92dc2420/utils/utils.go#L59)):*
> ```Go
> 
> func GetContextRequestString(context resources.RequestContext) string{
> 	return fmt.Sprintf("request-id=%s", context.Id)
> ```

consider to move it to logging module? since its logging thing.

I would consider even to move both request getNew and getContext string to logging, since the context is only for logging purposes (at least for now)

---

*[volume/provision.go, line 83 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-LEdevetC50sSrSS4jlb:-LEdeveuAGgf60v39_Wq:b7vmnzk) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e748541eb6f00cbdd12ec5f2f7cda22b92dc2420/volume/provision.go#L83)):*
> ```Go
> 	}
> 	provisioner := &flexProvisioner{
> 		logger:         logs.GetLogger(),
> ```

great please mention in the PR that you also fixed the provisioner to use the new logger vs the old one.

---

*[volume/provision.go, line 204 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-LEdfUt793G0oy5sGnjX:-LEdfUt793G0oy5sGnjY:bz72p80) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e748541eb6f00cbdd12ec5f2f7cda22b92dc2420/volume/provision.go#L204)):*
> ```Go
> 		err = p.ubiquityClient.RemoveVolume(removeVolumeRequest)
> 		if err != nil {
> 			msg := fmt.Sprintf("error removing volume")
> ```

i think you can skip using msg var, just put it in the logger

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/191)*

**Comment by shay-berman** [comment]
Finished the review - LGTM well done

---

Review status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @shay-berman and @olgashtivelman)

---

*[glide.yaml, line 12 at r3](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-LEoOxgZDxayE2TRyagH:-LEoOxgZDxayE2TRyagI:bbgj6jd) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/309b2473b42c6d9b291b71bb9e1e8e7776f7cf52/glide.yaml#L12)):*
> ```YAML
>   - lib
> - package: github.com/IBM/ubiquity
>   version: fix/UB-1099_add_request_id_to_all_logs
> ```

make sure before u merge to dev to change it back to dev

---

*[cmd/flex/main/cli.go, line 95 at r2](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-LEdbK8W0UPQ5wvQ9LDz:-LEoP1MmABdz62ta0Ci1:bxdkyl0) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/e748541eb6f00cbdd12ec5f2f7cda22b92dc2420/cmd/flex/main/cli.go#L95)):*
<details><summary><i>Previously, olgashtivelman wrote…</i></summary><blockquote>

OK since I don't have a logger here I will juist remove those prints to stdout
</blockquote></details>

yes, and BTW my guess is that the flex would not work due to this prints

---


*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-:-LEoPVxC7NzqSYycEFRo:b-2xe22d)*

**Comment by shay-berman** [comment]
:lgtm:

---

Reviewed 3 of 7 files at r1, 1 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed, 2 unresolved discussions (waiting on @olgashtivelman)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/191#-:-LEoPmr29p5FhvDGg5bQ:bnfp4nl)*

**Pull request merged**
