### PR TITLE
Fixes #140(fix log collection)  #141(timeout error message) +  #142(ICP increase timeout) + #144(docker images and license)

### LINKED ISSUE #140: Fix ubiquity_cli collect_logs : missing kubectl describe collection by label
Fix the "ubiquity_cli.sh" script so the "collect_logs" action will also collect the output of kubectl describe(and kubectl get) on all the ubiquity objects by  label (UB-409).
`kubectl describe $nsf ns,all,cm,secret,storageclass,pvc  -l product=ibm-storage-enabler-for-containers`

In addition, fixed missing label on the yamls/storage-class.yml.  Label it with product=ibm-storage-enabler-for-containers, since its part of the ubiquity installation objects.

### PR DESCRIPTION
**Pull request by shay-berman**
This pull request container the following fixes:
1. #140 : fix log collection to collect describe based on label
2. #141 : fix missing timeout error message during the installation
3. #142 : increase timeout per ICP request + some text alignment per @danapython 
4. #144 : Formal docker images from dockerhub + add license header to installer

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/145)

### CODE REVIEW

**Comment by liortamari** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/145#-:-KzrzoKELQCbw7U_LQpN:bnfp4nl)*

**Comment by alonm** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh, line 107 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/145#-KzrzOeJHqRP6SO_xsoy:-KzrzOeJHqRP6SO_xsoz:bebkpum) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d7b8e43a7c144b0a7a2a91a5221e68af1d5ba0cf/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh#L107)):*
> ```Shell
>     ubiquity_db_log_name=${logdir}/ubiquity-db.log
>     ubiquity_provisioner_log_name=${logdir}/ubiquity-k8s-provisioner.log
>     ubiquity_status_log_name=${logdir}/ubiquity_deployments_status
> ```

This is not a log file. rename the variable

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-k8s-flex-daemonset.yml, line 25 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/145#-Kzs3dtc1SAVJJ2_-rrF:-Kzs3dtc1SAVJJ2_-rrG:b-bnfwvb) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d7b8e43a7c144b0a7a2a91a5221e68af1d5ba0cf/scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-k8s-flex-daemonset.yml#L25)):*
> ```YAML
>       containers:
>       - name: ubiquity-k8s-flex
>         image: UBIQUITY_K8S_FLEX_IMAGE
> ```

Don't we want ibm-storage-enabler-for-containers label here as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/145)*

**Comment by shay-berman** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh, line 107 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/145#-KzrzOeJHqRP6SO_xsoy:-KzsAV2_A6iltAlG6Lp0:b-36ejcq) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d7b8e43a7c144b0a7a2a91a5221e68af1d5ba0cf/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh#L107)):*
<details><summary><i>Previously, alonm wrote…</i></summary><blockquote>

This is not a log file. rename the variable
</blockquote></details>

it is a log file. getting the logs from kubectl logs and put it inside a file.
So we all good here

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-k8s-flex-daemonset.yml, line 25 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/145#-Kzs3dtc1SAVJJ2_-rrF:-KzsAIojuJb441y5RAyv:bprzh84) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d7b8e43a7c144b0a7a2a91a5221e68af1d5ba0cf/scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-k8s-flex-daemonset.yml#L25)):*
<details><summary><i>Previously, alonm wrote…</i></summary><blockquote>

Don't we want ibm-storage-enabler-for-containers label here as well?
</blockquote></details>

I already added the label to the daemonset. look up in the metadata.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/145)*

**Comment by alonm** [comment]
*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh, line 107 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/145#-KzrzOeJHqRP6SO_xsoy:-Kzt1Krb_fjoNAK0OPBc:b-jhpa1y) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d7b8e43a7c144b0a7a2a91a5221e68af1d5ba0cf/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh#L107)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

it is a log file. getting the logs from kubectl logs and put it inside a file.
So we all good here
</blockquote></details>

Then it should have a .log suffix

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/145)*

**Comment by ranhrl** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/145#-:-L-_g2X_iN3RTEju-bix:bnfp4nl)*

**Pull request merged**
