### PR TITLE
Unify configmap + improve installer (USAGE & secrets & update-ymls)

### PR DESCRIPTION
**Pull request by shay-berman**
More details in the issue -> #112 

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/113)

### CODE REVIEW

**Comment by ranhrl** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[deploy/k8s_deployments/setup_flex.sh, line 49 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KxdKd46ADZsNa1UqI94:-KxdKd46ADZsNa1UqI95:b-4bmrn0) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/dc92df496d3866c1c0120f1d1a47b5cbacc4c911/deploy/k8s_deployments/setup_flex.sh#L49)):*
> ```Shell
> if [ -n "$LOG_LEVEL" ]; then
>     echo "Update \"logLevel\" in config file based on environment LOG_LEVEL"
>     sed -i "s/^logLevel =.*/logLevel = \"$LOG_LEVEL\"/" ${FLEX_TMP}
> ```

Instead of manipulating the file you could just generate it here, would be more robust don't you think? That way you can be sure no one edited it and changed it before hand.

---

*[scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml, line 8 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KxdL5mb_ok9JVMWY8Lc:-KxdL5mb_ok9JVMWY8Ld:b-u5naer) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/dc92df496d3866c1c0120f1d1a47b5cbacc4c911/scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml#L8)):*
> ```YAML
> data:
>    # SCBE server IP or FQDN.
>    SCBE-MANAGEMENT-IP: SCBE_MANAGEMENT_IP_VALUE
> ```

Should be management host and not ip

---

*[scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml, line 16 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KxdLx_d5s7jyBM119mu:-KxdLx_d5s7jyBM119mv:b-cb81ac) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/dc92df496d3866c1c0120f1d1a47b5cbacc4c911/scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml#L16)):*
> ```YAML
>    SCBE-DEFAULT-SERVICE: SCBE_DEFAULT_SERVICE_VALUE
> 
>    # Optional parameter. Default is 1.
> ```

The size for a new volume if not specified by the user when creating a new volume.

---

*[scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml, line 19 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KxdLO32IiPPvOju2ck8:-KxdLO32IiPPvOju2ck9:b1typky) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/dc92df496d3866c1c0120f1d1a47b5cbacc4c911/scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml#L19)):*
> ```YAML
>    DEFAULT-VOLUME-SIZE: 2
> 
>    # A prefix for any new volume created on the storage system. Default is none.
> ```

Is it really only the prefix? I think that the comment is misleading and imply that you can skip this value where in fact it is very important value. I would say: "Unique instance name for the service, maximum X characters." or something like that.

---

*[scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml, line 30 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KxdMNu6wuzW4gH5aFjX:-KxdMNu6wuzW4gH5aFjY:b-6sx6xn) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/dc92df496d3866c1c0120f1d1a47b5cbacc4c911/scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml#L30)):*
> ```YAML
> kind: ConfigMap
> metadata:
>   name: ubiquity-deployments-configmap
> ```

Mention that the name should not be changed.

---

*[scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml, line 49 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KxdNFUDz3DlI8-UAE1c:-KxdNFUDz3DlI8-UAE1d:b-lmvq9n) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/dc92df496d3866c1c0120f1d1a47b5cbacc4c911/scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml#L49)):*
> ```YAML
> 
>    # Password defined for SCBE Ubiquity interface.
>    password: "SCBE_PASSWORD_VALUE"
> ```

Is it ok to keep passwords in the config map? is it encrypted?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113)*

**Comment by ranhrl** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113)*

**Comment by shay-berman** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[deploy/k8s_deployments/setup_flex.sh, line 49 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KxdKd46ADZsNa1UqI94:-KxdfFgghY2LchDpoGog:b-kvmtvo) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/dc92df496d3866c1c0120f1d1a47b5cbacc4c911/deploy/k8s_deployments/setup_flex.sh#L49)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

Instead of manipulating the file you could just generate it here, would be more robust don't you think? That way you can be sure no one edited it and changed it before hand.
</blockquote></details>

I prefer to leave it open, for Scale, so they can add what ever param them wants later on.
so the conf file is the default and i manipulate it for change the defaults

---

*[scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml, line 8 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KxdL5mb_ok9JVMWY8Lc:-KxdfZ9MP7mZOUrDCIgR:brhkl4l) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/dc92df496d3866c1c0120f1d1a47b5cbacc4c911/scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml#L8)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

Should be management host and not ip
</blockquote></details>

of SCBE_HOST
lets give Dime to define it, now that we have single file it should be easier for him.

---

*[scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml, line 16 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KxdLx_d5s7jyBM119mu:-KxdgDfBPT3JCWBLwsNO:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/dc92df496d3866c1c0120f1d1a47b5cbacc4c911/scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml#L16)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

The size for a new volume if not specified by the user when creating a new volume.
</blockquote></details>

Done.

---

*[scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml, line 19 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KxdLO32IiPPvOju2ck8:-KxdgW52R2WbqdfSseiA:boy1m74) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/dc92df496d3866c1c0120f1d1a47b5cbacc4c911/scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml#L19)):*
> "Unique instance name for the service
lets consult with Dima here

---

*[scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml, line 30 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KxdMNu6wuzW4gH5aFjX:-KxdgdGEH9TMULpUdGZ3:b-uvx1tr) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/dc92df496d3866c1c0120f1d1a47b5cbacc4c911/scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml#L30)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

Mention that the name should not be changed.
</blockquote></details>

I think its obvious, we can say it on a lot of items.  
only the params are for edit. 

---

*[scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml, line 49 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KxdNFUDz3DlI8-UAE1c:-KxdgsHyNAHQO6zj0mww:bq7r371) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/dc92df496d3866c1c0120f1d1a47b5cbacc4c911/scripts/k8s_scbe_all_in_one/ubiquity-configmaps.yml#L49)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

Is it ok to keep passwords in the config map? is it encrypted?
</blockquote></details>

as mentioned in the TODO, its the first step, after it works with configmap i will switch it to secret.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113)*

**Comment by midoblgsm** [comment]
Reviewed 2 of 8 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[scripts/k8s_scbe_all_in_one/ubiquity_uninstall.sh, line 126 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KxlwN_lHSwzlydbuBHd:-KxlwN_lHSwzlydbuBHe:b-c6xjis) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d4dd4466feef29fda91bd5693fe2b9be1c2784e3/scripts/k8s_scbe_all_in_one/ubiquity_uninstall.sh#L126)):*
> ```Shell
> $kubectl_delete -f $YML_DIR/ubiquity-db-service.yml
> $kubectl_delete -f $YML_DIR/ubiquity-namespace.yml
> ```

would you like to delete the credentials as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113)*

**Comment by shay-berman** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[scripts/k8s_scbe_all_in_one/ubiquity_uninstall.sh, line 126 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KxlwN_lHSwzlydbuBHd:-Kxnr9NGdipHsQmyGOzE:bioemq3) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d4dd4466feef29fda91bd5693fe2b9be1c2784e3/scripts/k8s_scbe_all_in_one/ubiquity_uninstall.sh#L126)):*
<details><summary><i>Previously, midoblgsm (Mohamed Mohamed) wrote…</i></summary><blockquote>

would you like to delete the credentials as well?
</blockquote></details>

good catch
thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113)*

**Comment by alonm** [comment]
Review status: 1 of 24 files reviewed at latest revision, 15 unresolved discussions, some commit checks broke.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/scbe-credentials.yml, line 5 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyB90emJPT8tS5VEflO:-KyB90emJPT8tS5VEflP:b1pha15) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/scbe-credentials.yml#L5)):*
> ```YAML
> metadata:
>   name: scbe-credentials
> # SCBE credential needed for deployments : ubiquity, ubiquity-k8s-provisioner and ubiquity-k8s-flex
> ```

nit: SCBE credentials

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/scbe-credentials.yml, line 8 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyB9KXliSNAbYtUH8NR:-KyB9KXliSNAbYtUH8NS:bhfx4i8) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/scbe-credentials.yml#L8)):*
> ```YAML
> type: Opaque
> data:
>    # Base64 encoded of the user name defined for SCBE Ubiquity interface
> ```

Base64 encoded user name ...

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/scbe-credentials.yml, line 11 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyB9Pee7hPSDxlRz0r_:-KyB9Pee7hPSDxlRz0ra:bf164w7) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/scbe-credentials.yml#L11)):*
> ```YAML
>    username: "SCBE_USERNAME_VALUE"
> 
>    # Base64 encoded of the Password defined for SCBE Ubiquity interface.
> ```

Base64 encoded Password ...

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 4 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyB9_q8uNHwa1Mouiu6:-KyB9_q8uNHwa1Mouiu7:b5vwihk) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L4)):*
> ```YAML
> kind: ConfigMap
> metadata:
> # Setting for Ubiquity deployment
> ```

Settings ..

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 8 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyB9n69zHMenOt9jD_Y:-KyB9n69zHMenOt9jD_Z:b-9xxfjj) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L8)):*
> ```YAML
> data:
>    # SCBE server IP or FQDN.
>    SCBE-MANAGEMENT-IP: SCBE_MANAGEMENT_IP_VALUE
> ```

If it can be FQDN why not call it SCBE-MANAGEMENT-FQDN and SCBE_MANAGEMENT_FQDN_VALUE?

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 16 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyBA8IV2swutS2mc24m:-KyBA8IV2swutS2mc24n:bvu85m7) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L16)):*
> ```YAML
>    SCBE-DEFAULT-SERVICE: SCBE_DEFAULT_SERVICE_VALUE
> 
>    # Optional parameter. Default is 1GB. The size for a new volume if not specified by the user when creating a new volume.
> ```

Default is 1GB according to text but the actual value is 2. 

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-db-credentials.yml, line 17 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyBASd22xo6N7hE1Juz:-KyBASd22xo6N7hE1Jv-:b48hgck) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-db-credentials.yml#L17)):*
> ```YAML
>    password: "UBIQUITY_DB_PASSWORD_VALUE"
> 
>    # Base64 encoded of the DB name(be default is "ubiquity") that will be created on the ubiquity-db
> ```

Base64 encoded database name (default is "ubiquity) ...

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh, line 13 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyBAfqjMwjPP6t6012h:-KyBAfqjMwjPP6t6012i:bwtblxx) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh#L13)):*
> ```Shell
> #   3. Create ubiquity-k8s-provisioner deployment
> #   4. Create ubiquity-k8s-flex Daemonset
> #   4. Create ubiquity-db-deployment deployment  (last one because it uses PVC, so ubiquity must go up before)
> ```

... (last step. Uses PVC, so Ubiqiuty server must be up)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113)*

**Comment by shay-berman** [comment]
Review status: 1 of 24 files reviewed at latest revision, 15 unresolved discussions, some commit checks broke.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/scbe-credentials.yml, line 5 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyB90emJPT8tS5VEflO:-KyBBx0BvXuatXgJ9uzm:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/scbe-credentials.yml#L5)):*
<details><summary><i>Previously, alonm wrote…</i></summary><blockquote>

nit: SCBE credentials
</blockquote></details>

Done.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/scbe-credentials.yml, line 8 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyB9KXliSNAbYtUH8NR:-KyBBwbhr982n7ONlzbQ:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/scbe-credentials.yml#L8)):*
<details><summary><i>Previously, alonm wrote…</i></summary><blockquote>

Base64 encoded user name ...
</blockquote></details>

Done.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/scbe-credentials.yml, line 11 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyB9Pee7hPSDxlRz0r_:-KyBBwLde9BeTj3ol3X3:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/scbe-credentials.yml#L11)):*
<details><summary><i>Previously, alonm wrote…</i></summary><blockquote>

Base64 encoded Password ...
</blockquote></details>

Done.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 4 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyB9_q8uNHwa1Mouiu6:-KyBBvpWRVteTPGyOWgi:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L4)):*
<details><summary><i>Previously, alonm wrote…</i></summary><blockquote>

Settings ..
</blockquote></details>

Done.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 8 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyB9n69zHMenOt9jD_Y:-KyBBnkHQWarnkBFKypB:b-yva9t9) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L8)):*
> credentials
will not change it now
there is open ticket for Dima to review the param texts, so lets give Dima to decide on that.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 16 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyBA8IV2swutS2mc24m:-KyBC62r2RTedLWA999i:b-8eae33) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L16)):*
> Default is 1GB according to text but the actual value is 2.
ok good
changing it to 1
anyway the customer will not really use this config because in k8s you must specific the size. this is why i set it here and didn't provide placeholder in the ubiquity.config file

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-db-credentials.yml, line 17 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyBASd22xo6N7hE1Juz:-KyBCSOkV8KB5izubH5y:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-db-credentials.yml#L17)):*
<details><summary><i>Previously, alonm wrote…</i></summary><blockquote>

Base64 encoded database name (default is "ubiquity) ...
</blockquote></details>

Done.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh, line 13 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113#-KyBAfqjMwjPP6t6012h:-KyBCt_mhsMegzcSjL-C:b-896fix) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/9bf7864992a11302cab132397ce732c6abae8409/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh#L13)):*
<details><summary><i>Previously, alonm wrote…</i></summary><blockquote>

... (last step. Uses PVC, so Ubiqiuty server must be up)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/113)*

**Pull request merged**
