### PR TITLE
Flex init no logging + set loglevel + daemonset imagePullPolicy use default and not Always

### PR DESCRIPTION
**Pull request by liortamari**
1. Remove logging from the flex init function (to reduce the init noise)
2. Fix log level setting in the flex
3. Daemonset should use the default imagePullPolicy instead of Always

This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/152)

### CODE REVIEW

**Comment by ranhrl** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/152#-L-gUxzZZUGKVAJ8X8CD:-L-gUxzZZUGKVAJ8X8CE:bf189cc) (no related file):*
 I don't really understand, what has changed that we now don't need to do all those inits?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/152)*

**Comment by ranhrl** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/152#-:-L-gVd45PH8_3851cSfu:bnfp4nl)*

**Comment by shay-berman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/flex/main/cli.go, line 82 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/152#-L-j8PxdP1-O4xQr8vNj:-L-j8PxdP1-O4xQr8vNk:b-m54llv) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d93a85deaefa4a1f0fbeca733797313c59261f88/cmd/flex/main/cli.go#L82)):*
> ```Go
> 		return printResponse(response)
> 	}
> 	response := controller.Init(config)
> ```

please explain why remove these lines will improve something?
anyway it returns the successful response, if nothing was wrong.

So is there any error flex getting until it returns the successful response? if so what was the error and when.
Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/152)*

**Comment by ranhrl** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/flex/main/cli.go, line 82 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/152#-L-j8PxdP1-O4xQr8vNj:-L-jnJWipC_lKc7oW5k_:b1ou5) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d93a85deaefa4a1f0fbeca733797313c59261f88/cmd/flex/main/cli.go#L82)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

please explain why remove these lines will improve something?
anyway it returns the successful response, if nothing was wrong.

So is there any error flex getting until it returns the successful response? if so what was the error and when.
Thanks
</blockquote></details>

According to a conversation I had with Lior, these lines are not required anymore and the controller.Init is not required, all it does is to print a lot of info messages to the log

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/152)*

**Comment by shay-berman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/flex/main/cli.go, line 82 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/152#-L-j8PxdP1-O4xQr8vNj:-L-krq0TJZMmVgH0BJCH:b-wam465) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d93a85deaefa4a1f0fbeca733797313c59261f88/cmd/flex/main/cli.go#L82)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

According to a conversation I had with Lior, these lines are not required anymore and the controller.Init is not required, all it does is to print a lot of info messages to the log
</blockquote></details>

but we should have at lease debug log as trace to this function, other wise we will not be aware if k8s call us for init.
i would even put it as info.
Before making this change, please try to identify why k8s sending us so many init request?  do we have a bug that fail instead returning the right response for k8s?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/152)*

**Comment by ranhrl** [comment]
*[cmd/flex/main/cli.go, line 82 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/152#-L-j8PxdP1-O4xQr8vNj:-L-l8gXumKy9wCm__NP1:b2c60mm) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d93a85deaefa4a1f0fbeca733797313c59261f88/cmd/flex/main/cli.go#L82)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

but we should have at lease debug log as trace to this function, other wise we will not be aware if k8s call us for init.
i would even put it as info.
Before making this change, please try to identify why k8s sending us so many init request?  do we have a bug that fail instead returning the right response for k8s?
</blockquote></details>

we don't know why and couldn't find why

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/152)*

**Comment by shay-berman** [comment]
- Due to inputs in [PR](https://github.com/IBM/ubiquity-k8s/pull/153#issuecomment-350487425) we will go with this PR.

- I tested it now and it works ok, means no logs during init. 

Two more things to do :
1. We may consider to do the same silence in GetVolumeName since it called a lot of times and print few debugs.
2. I think we have a bug, because we are not using the log level in flex, instead it looks like we use always DEBUG. https://github.com/IBM/ubiquity-k8s/blob/dev/cmd/flex/main/cli.go#L73

**Comment by ranhrl** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/152#-:-L-wlTS82fGBCamyS2YY:bnfp4nl)*

**Pull request merged**
