### PR TITLE
ubiquity-db pv name as configurable parameter for the installer (to support DS8K)

### PR DESCRIPTION
**Pull request by hfeish**
Change:
    In ubiquity 1.0.0, ibm-ubiquity-db is a hardcord pv name, but to support DS8k which has volume name length limitation about 16 chars, so we change design about ubiquity db name, make it configurable in ubiquity_installer.conf and ubiquity-configmap.yml, so customer can set the default name "ibm-ubiquity-db" to example "ibmdb" if the backend storage is DS8k

How to test:
basic testing:
   1. The default db name works on SVC/XIV, and not works on DS8k
   2. Change default db name to "ibmdb" and make sure it works on DS8k
   3. Change db name to "ibm-ubiquity-db-test", and it should also works on SVC/XIV
   4. Verify uninstall successfully

upgrade testing:
  steps:
        Had ubiquity 1.0.0 installed, backend storage is SVC/XIV
        Upgrade ubiquity-configmap.yml with ubiquity_installer.conf(use default db name)
        Upgrade configmap with new ubiquity-configmap yml
        Upgrade Ubiquity and Provisioner Pod
        Make sure everything works fine

Documents:
     1.  ibm-ubiquity-db is the default db name for SVC/XIV, for DS8k, we suggest to use ibmdb, also customer should know that db name: u_{instance}_ibmdb should less than 17 chars
     2. if customer want to create pv in DS8k, customer need to set pv name with pv-name label in pvc, otherwize it will fail to create pvc because DS8k has 16 chars limitation
     3. Need to tell customer how to do upgrade

Signed-off-by: feihuang <feihuang@feihuangs-mbp.cn.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/167)

### CODE REVIEW

**Comment by shay-berman** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml, line 29 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-L4lJ3FrB0wwiaUGkzQ2:-L4lJ3FrB0wwiaUGkzQ3:b-w7gon9) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d88f52f142450439b7544868862d3358015d4b65/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity-configmap.yml#L29)):*
> ```YAML
>    DEFAULT-FSTYPE: DEFAULT_FSTYPE_VALUE
> 
>    # Ubiquity db pv name, For SVC/XIV, use default value. For DS8k, please set a short name, ex: ibmdb, because DS8k has a limitation for 16 chars volume name
> ```

don't instruct here to set the param, because this param cannot be changed after the first installation.
The explanation should be in the ubiquiyt_installer.conf.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh, line 163 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-L4lJOKKLtNHmXDxRPxA:-L4lJOKKLtNHmXDxRPxB:b-lrc199) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d88f52f142450439b7544868862d3358015d4b65/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh#L163)):*
> ```Shell
>     echo ""
> 
>     pvname=`kubectl get $nsf pvc ${UBIQUITY_DB_PVC_NAME} --no-headers -o custom-columns=name:spec.volumeName`
> ```

what about the pvc name? don't we align it with the PV name?

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_installer.conf, line 40 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-L4lJdmf0IaosLGvd6vp:-L4lJdmf0IaosLGvd6vq:b-2krxtv) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d88f52f142450439b7544868862d3358015d4b65/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_installer.conf#L40)):*
> ```
> 
> # Parameters in ubiquity-configmap.yml that impact on ubiquity db volume
> #-----------------------------------------------------------------
> ```

# Param...
#--------------------
not sure you need this comments

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_installer.sh, line 198 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-L4lKaEvasi0QX7F5HZY:-L4lKaEvasi0QX7F5HZZ:bog1adm) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d88f52f142450439b7544868862d3358015d4b65/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_installer.sh#L198)):*
> ```Shell
>     KEY_FILE_DICT['UBIQUITY_K8S_FLEX_IMAGE']="${UBIQUITY_FLEX_DAEMONSET_YML}"
>     KEY_FILE_DICT['SCBE_MANAGEMENT_IP_VALUE']="${UBIQUITY_CONFIGMAP_YML}"
>     KEY_FILE_DICT['SCBE_MANAGEMENT_PORT_VALUE']="${UBIQUITY_CONFIGMAP_YML}"
> ```

r u sure nothing need to be change in the uninstall?  probably no, but please check

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-db-pvc.yml, line 4 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-L4lKH1n3aHrbuAhjwhq:-L4lKH1n3aHrbuAhjwhr:b-kgfyed) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d88f52f142450439b7544868862d3358015d4b65/scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-db-pvc.yml#L4)):*
> ```YAML
> apiVersion: v1
> metadata:
>   name: "ibm-ubiquity-db"
> ```

I am not sure, maybe its better to align also the pvc name according to the pv?
not sure, please consider the implication if any.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-db-pvc.yml, line 8 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-L4lK1FRy4z9WBfGLdd2:-L4lK1FS9py1q9JM81v1:b-dksi1y) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d88f52f142450439b7544868862d3358015d4b65/scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-db-pvc.yml#L8)):*
> ```YAML
>     volume.beta.kubernetes.io/storage-class: "STORAGE_CLASS_NAME_VALUE"
>   labels:
>     pv-name: "IBM_UBIQUITY_DB_PV_NAME_VALUE"   # Ubiquity provisioner will create a PV with ibm-ubiquity-db instead of PVC-ID by default.
> ```

change the comment : "ibm-ubiquity-db" -> <pv-name>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167)*

**Comment by shay-berman** [comment]
FYI : I also update a bit the PR name and description to clarify the change.

**Comment by shay-berman** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167)*

**Comment by hfeish** [comment]
@shay-berman , Do we need to change pvc name? I think pvc name is a claim for PV, so why not we keep the consistent name for SVC/XIV/DS8k, and also make ibm-ubiquity-db as a specific name for ibm ubiquity db claim.

**Comment by shay-berman** [comment]
Review status: 3 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh, line 163 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-L4lJOKKLtNHmXDxRPxA:-L4sy2JLBMt14pwYPRJY:b-urgj98) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d88f52f142450439b7544868862d3358015d4b65/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_cli.sh#L163)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

what about the pvc name? don't we align it with the PV name?
</blockquote></details>

ok so we can keep the PVC with the original name and only change the PV name if needed.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_installer.conf, line 39 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-L6QXm-4jgfeEVvkMDEz:-L6QXm-5KbB0ARrfybPj:bhwpbur) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/160f1c8b87d926864cb406881b1ee359e79f0a75/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_installer.conf#L39)):*
> ```
> DEFAULT_VOLUME_SIZE_VALUE=1
> 
> # Ubiquity db pv name, For SVC/XIV, use default value. For DS8k, please set a short name, ex: ibmdb, because DS8k has a limitation for 16 chars volume name
> ```

ex -> e.g:

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_installer.sh, line 198 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-L4lKaEvasi0QX7F5HZY:-L6QXHxCXIC386tA0R1H:b-xvrqv5) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d88f52f142450439b7544868862d3358015d4b65/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_installer.sh#L198)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

r u sure nothing need to be change in the uninstall?  probably no, but please check
</blockquote></details>

update - since we only change the PV name, no need to update the uninstall.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-db-pvc.yml, line 4 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-L4lKH1n3aHrbuAhjwhq:-L4syHV36x0iFAb_OGhb:b-qpkrj6) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d88f52f142450439b7544868862d3358015d4b65/scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-db-pvc.yml#L4)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

I am not sure, maybe its better to align also the pvc name according to the pv?
not sure, please consider the implication if any.
</blockquote></details>

Fie, make sure uninstall align with the new PV configuration (it should be because we just delete the PVC but please double check it)

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-db-pvc.yml, line 8 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-L4lK1FRy4z9WBfGLdd2:-L4syjd15gQXs9W_r7gM:b-7g7swp) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d88f52f142450439b7544868862d3358015d4b65/scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-db-pvc.yml#L8)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

change the comment : "ibm-ubiquity-db" -> <pv-name>
</blockquote></details>

the comment should be : Ubiquity provisioner will create a PV with dedicated name (by default its ibm-ubiquity-db)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167)*

**Comment by hfeish** [comment]
Review status: 3 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_installer.conf, line 39 at r3](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-L6QXm-4jgfeEVvkMDEz:-L6UNMQocjpg7cWEoI0k:b-n9tkhd) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/160f1c8b87d926864cb406881b1ee359e79f0a75/scripts/installer-for-ibm-storage-enabler-for-containers/ubiquity_installer.conf#L39)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

ex -> e.g:
</blockquote></details>

changed

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-db-pvc.yml, line 4 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-L4lKH1n3aHrbuAhjwhq:-L6UN_Pz7b5V7vw-T0ko:b-kntsk6) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d88f52f142450439b7544868862d3358015d4b65/scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-db-pvc.yml#L4)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

Fie, make sure uninstall align with the new PV configuration (it should be because we just delete the PVC but please double check it)
</blockquote></details>

Yudai tested uninstall in DS8k, and zhiyuan tested uninstall after upgrade from 1.0.0 to 1.1.0, both successful

---

*[scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-db-pvc.yml, line 8 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-L4lK1FRy4z9WBfGLdd2:-L6UNYJJ3mToZKAIJViU:bb6un1j) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/d88f52f142450439b7544868862d3358015d4b65/scripts/installer-for-ibm-storage-enabler-for-containers/yamls/ubiquity-db-pvc.yml#L8)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

the comment should be : Ubiquity provisioner will create a PV with dedicated name (by default its ibm-ubiquity-db)
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167)*

**Comment by shay-berman** [comment]
:lgtm:

Thanks @Fei
Please merge to dev

---

Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/167#-:-L6Vc8vlSUJ7U-6jeNaD:b-36rnw)*

**Comment by hfeish** [comment]
Merge and close

**Pull request merged**
