### PR TITLE
Scbe align for k8s (flexvolume umount and also provisioner size)

### PR DESCRIPTION
**Pull request by shay-berman**
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/38)

### CODE REVIEW

**Comment by shay-berman** [comment]
@midoblgsm  I created the PR so u can review the code so far.
i still need to add more unit testing commit tomorrow and add the vendor/ubiquity util also inside the ubiquity original repository.

just review it for now and tomorrow i will apply the above as well.

**Comment by midoblgsm** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[controller/controller.go, line 229 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/38#-Kpw5uveWMbhpkM3HwNE:-Kpw5uveWMbhpkM3HwNF:b-wmso3m) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f9be670c4e952390a584f19dd32267252d2fa191/controller/controller.go#L229)):*
> ```Go
> 
> 	// Validate that the mountpoint is a symlink as ubiquity expect it to be
> 	realMountPoint, err := c.exec.EvalSymlinks(unmountRequest.MountPath)
> ```

This should be implemented in ubiquity, otherwise it will be broken in the next glide up

---

*[controller/controller.go, line 253 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/38#-Kpw7-s9bcumjfRaBSyA:-Kpw7-s9bcumjfRaBSyB:bekue1q) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f9be670c4e952390a584f19dd32267252d2fa191/controller/controller.go#L253)):*
> ```Go
> 
> 		c.logger.Println(fmt.Sprintf("Removing the slink [%s] to the real mountpoint [%s]", unmountRequest.MountPath, realMountPoint))
> 		err := c.exec.Remove(unmountRequest.MountPath)
> ```

This should be implemented in ubiquity

---

*[vendor/github.com/IBM/ubiquity/fakes/fake_executor.go, line 1 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/38#-Kpw7oP3GAv1iX_rWmD1:-Kpw7oP4yuIqeFAMe7LR:b-z1amz3) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f9be670c4e952390a584f19dd32267252d2fa191/vendor/github.com/IBM/ubiquity/fakes/fake_executor.go#L1)):*
>  
Please do not change anything inside the vendor directory, all your changes will get lost in the next glide up
All changes should go to ubiquity repo then bump ubiquity-k8s to the latest ubiquity
Once this is done, don't forget to point glide.yml to the right branch of ubiquity

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/38)*

**Comment by shay-berman** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[controller/controller.go, line 229 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/38#-Kpw5uveWMbhpkM3HwNE:-KpxCJ9JqjF2lFRM-WBL:b-qhjbym) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f9be670c4e952390a584f19dd32267252d2fa191/controller/controller.go#L229)):*
<details><summary><i>Previously, midoblgsm (Mohamed Mohamed) wrote…</i></summary><blockquote>

This should be implemented in ubiquity, otherwise it will be broken in the next glide up
</blockquote></details>

yes, this what i told u in the comment above. i am now pushing the relevat to ubiquity and update it in k8s side.

---

*[controller/controller.go, line 253 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/38#-Kpw7-s9bcumjfRaBSyA:-KpxCVfSremv_1Ep5Q3Z:bnj7hl0) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/f9be670c4e952390a584f19dd32267252d2fa191/controller/controller.go#L253)):*
<details><summary><i>Previously, midoblgsm (Mohamed Mohamed) wrote…</i></summary><blockquote>

This should be implemented in ubiquity
</blockquote></details>

same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/38)*

**Comment by liortamari** [comment]
Reviewed 6 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/38)*

**Pull request merged**
