### PR TITLE
Feature/installer with plugin scbe credentials and certificates readiness

### PR DESCRIPTION
**Pull request by shay-berman**
**Support Ubiquity certificates:**
1. Align all ymls with plumbing to certificates secrets and configmap.
   YMLS : ubiquity,      ubiquity-db,     ubiquity-provisioner,     ubiqutiy-flex-deamonset
2. Align the install script to support certificates stage (allow to deploy only services to see the IP in order to create certificates)
3. Support the new SSL_MODE and remove all the none relevant ENVs that are now hardcoded per https://github.com/IBM/ubiquity/pull/134

**support for SCBE authorization** 
from the plugin side. and all the plumbing to deliver the credential to provisioner and also to the flex (which is actually deliver it to the host it self)

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ubiquity-k8s/105)

### CODE REVIEW

**Comment by ranhrl** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[deploy/k8s_deployments/setup_flex.sh, line 37 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kwdx1cQvXlndtN6NAM-:-Kwdx1cQvXlndtN6NAM0:b-s4li8o) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ed12c395883c57cac60a82b63586dfe9ee675987/deploy/k8s_deployments/setup_flex.sh#L37)):*
> ```Shell
> fi
> if [ -n "$UBIQUITY_PLUGIN_USE_SSL" ]; then
>     echo "Update \"UseSsl\" in config file based on environment UBIQUITY_PLUGIN_USE_SSL"
> ```

Is it case sensitive?
If so, then at least comply to a convention with all the parameters and also for SSL / CA use capital letters

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105)*

**Comment by shay-berman** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[deploy/k8s_deployments/setup_flex.sh, line 37 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kwdx1cQvXlndtN6NAM-:-Kx4IZUyZ8bJQUzZmENg:b-pdlsx3) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ed12c395883c57cac60a82b63586dfe9ee675987/deploy/k8s_deployments/setup_flex.sh#L37)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

Is it case sensitive?
If so, then at least comply to a convention with all the parameters and also for SSL / CA use capital letters
</blockquote></details>

UseSsl is case sensitive. its a name of the variable in go. all the params in the flex config in the same conversion.
Any suggestion I should apply?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105)*

**Comment by ranhrl** [comment]
There should be a task for Dima to review every setting name and text displayed to the user.

---

Reviewed 7 of 7 files at r1.
Review status: 1 of 11 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[cmd/flex/main/cli.go, line 623 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kx7dR7pVwMENxjEXINH:-Kx7dR7pVwMENxjEXINI:bd2ih9c) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/4b83c7f1f936af0d26e9fcde7025175dcb64275b/cmd/flex/main/cli.go#L623)):*
> ```Go
> 	// Create environment variables for some of the config params
> 	os.Setenv(remote.KeyUseSsl,  strconv.FormatBool(config.SslConfig.UseSsl))
> 	os.Setenv(resources.KeySslMode,  strconv.FormatBool(config.SslConfig.SslMode))
> ```

Why is this boolean?

---

*[deploy/k8s_deployments/setup_flex.sh, line 37 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kwdx1cQvXlndtN6NAM-:-Kx7e0PITY2bVTqpz0Qe:bxcck9s) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ed12c395883c57cac60a82b63586dfe9ee675987/deploy/k8s_deployments/setup_flex.sh#L37)):*
<details><summary><i>Previously, shay-berman wrote…</i></summary><blockquote>

UseSsl is case sensitive. its a name of the variable in go. all the params in the flex config in the same conversion.
Any suggestion I should apply?
</blockquote></details>

If the convention is camelcase then UseSSL and SSLMode

---

*[deploy/k8s_deployments/setup_flex.sh, line 25 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kx7d_cQIqaGET13sk8M:-Kx7d_cQIqaGET13sk8N:bb38wul) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/4b83c7f1f936af0d26e9fcde7025175dcb64275b/deploy/k8s_deployments/setup_flex.sh#L25)):*
> ```Shell
> mv -f "${MNT_FLEX_DRIVER_DIR}/.$DRIVER" "${MNT_FLEX_DRIVER_DIR}/$DRIVER"
> 
> echo "Copying the flex config file ${FLEX_CONF_PATH} to ${ETC_UBIQUITY}/${FLEX_CONF}"
> ```

This path needs to change in favor of the controller container and it might worth doing it now. If you don't change it, you will have to mount two volumes for the controller, one for the etc directory (conf file) and the other for the plugin itself. I suggest putting the config file in the same directory as the binary flex file.

---

*[scripts/k8s_scbe_all_in_one/yamls/ubiquity-deployment.yml, line 66 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kx7fCzQKHp8IgNOH_IR:-Kx7fCzQKHp8IgNOH_IS:bmz2qtd) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/4b83c7f1f936af0d26e9fcde7025175dcb64275b/scripts/k8s_scbe_all_in_one/yamls/ubiquity-deployment.yml#L66)):*
> ```YAML
>             value: "scbe"
> 
> #          - name: UBIQUITY_SERVER_CERT_PUBLIC
> ```

Do we need those two in the yaml? we don't recommend to change the path right?

---

*[scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-flex-daemonset.yml, line 37 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kx7fy47ZGEPVR8faZ7G:-Kx7fy47ZGEPVR8faZ7H:bqlrywg) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/4b83c7f1f936af0d26e9fcde7025175dcb64275b/scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-flex-daemonset.yml#L37)):*
> ```YAML
> 
> #          - name: UBIQUITY_PLUGIN_VERIFY_CA
> #            value: "/var/lib/ubiquity/ssl/public/ubiquity-trusted-ca.crt"
> ```

Same here, do we want to expose the fact that the path can be changed with this parameter?

---

*[scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-flex.conf, line 11 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kx7g5RndVukZT1DT5SF:-Kx7g5RndVukZT1DT5SG:bygoi8p) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/4b83c7f1f936af0d26e9fcde7025175dcb64275b/scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-flex.conf#L11)):*
> ```
> [CredentialInfo]
> username = "UBIQUITY_USERNAME_VALUE"
> password = "UBIQUITY_USERNAME_VALUE"
> ```

UBIQUITY_PASSWORD_VALUE

---

*[scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-flex.conf, line 18 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kx7gDkb-vDmweyBqydF:-Kx7gDkb-vDmweyBqydG:bgt3oo6) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/4b83c7f1f936af0d26e9fcde7025175dcb64275b/scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-flex.conf#L18)):*
> ```
> [SslConfig]
> SslMode = "verify-full"  # require or verify-full
> VerifyCa = "/etc/ubiquity/ubiquity-trusted-ca.crt"  # Relevant only if SslMode is verify-full
> ```

VerifyCA if possible to change it

---

*[scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-provisioner-deployment.yml, line 48 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kx7gS7jsJayVn_ID7ps:-Kx7gS7jsJayVn_ID7pt:b-1rn4gw) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/4b83c7f1f936af0d26e9fcde7025175dcb64275b/scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-provisioner-deployment.yml#L48)):*
> ```YAML
> 
>           - name: UBIQUITY_PASSWORD
>             value: "UBIQUITY_USERNAME_VALUE"
> ```

PASSWORD

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-:-Kx7gZ3vUP-1DOfaZUgZ:b-f3zaps)*

**Comment by shay-berman** [comment]
Review status: 1 of 12 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[cmd/flex/main/cli.go, line 623 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kx7dR7pVwMENxjEXINH:-Kx7wD4_IcAbff9JN25C:b-6tp54p) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/4b83c7f1f936af0d26e9fcde7025175dcb64275b/cmd/flex/main/cli.go#L623)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

Why is this boolean?
</blockquote></details>

already fixed

---

*[deploy/k8s_deployments/setup_flex.sh, line 37 at r1](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kwdx1cQvXlndtN6NAM-:-Kx7zYeFNldTTZN1H34O:b-ylblsh) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/ed12c395883c57cac60a82b63586dfe9ee675987/deploy/k8s_deployments/setup_flex.sh#L37)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

If the convention is camelcase then UseSSL and SSLMode
</blockquote></details>

this is the conversion we use in ubiquity, i will keep that.

---

*[deploy/k8s_deployments/setup_flex.sh, line 25 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kx7d_cQIqaGET13sk8M:-Kx7zKJxyfx_4rFtddm0:b-6xkymb) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/4b83c7f1f936af0d26e9fcde7025175dcb64275b/deploy/k8s_deployments/setup_flex.sh#L25)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

This path needs to change in favor of the controller container and it might worth doing it now. If you don't change it, you will have to mount two volumes for the controller, one for the etc directory (conf file) and the other for the plugin itself. I suggest putting the config file in the same directory as the binary flex file.
</blockquote></details>

opened ticket to do this good suggestion.  stretched to this GA v1.

---

*[scripts/k8s_scbe_all_in_one/yamls/ubiquity-deployment.yml, line 66 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kx7fCzQKHp8IgNOH_IR:-Kx80-XlGc_zGhtHjcA7:bgdjivs) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/4b83c7f1f936af0d26e9fcde7025175dcb64275b/scripts/k8s_scbe_all_in_one/yamls/ubiquity-deployment.yml#L66)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

Do we need those two in the yaml? we don't recommend to change the path right?
</blockquote></details>

will remove it before the GA.   I added a comment in a ticket for doing it.

---

*[scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-flex-daemonset.yml, line 37 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kx7fy47ZGEPVR8faZ7G:-Kx805hadf89-mwJgCTr:bb7od0r) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/4b83c7f1f936af0d26e9fcde7025175dcb64275b/scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-flex-daemonset.yml#L37)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

Same here, do we want to expose the fact that the path can be changed with this parameter?
</blockquote></details>

same

---

*[scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-flex.conf, line 11 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kx7g5RndVukZT1DT5SF:-Kx80OiNCgjnvPPVIau6:b-qssebl) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/4b83c7f1f936af0d26e9fcde7025175dcb64275b/scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-flex.conf#L11)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

UBIQUITY_PASSWORD_VALUE
</blockquote></details>

fixed.

---

*[scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-flex.conf, line 18 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kx7gDkb-vDmweyBqydF:-Kx80XLGygaLofAvEmnI:b-6zejvq) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/4b83c7f1f936af0d26e9fcde7025175dcb64275b/scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-flex.conf#L18)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

VerifyCA if possible to change it
</blockquote></details>

will keep the current convension

---

*[scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-provisioner-deployment.yml, line 48 at r2](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105#-Kx7gS7jsJayVn_ID7ps:-Kx80jZAmUAd-KV2o7ZO:b5zdhlx) ([raw file](https://github.com/ibm/ubiquity-k8s/blob/4b83c7f1f936af0d26e9fcde7025175dcb64275b/scripts/k8s_scbe_all_in_one/yamls/ubiquity-k8s-provisioner-deployment.yml#L48)):*
<details><summary><i>Previously, ranhrl (Ran Harel) wrote…</i></summary><blockquote>

PASSWORD
</blockquote></details>

very good
thanks for the catch!
fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ibm/ubiquity-k8s/105)*

**Pull request merged**
